package cn.gov.enterprise.modules.organization.approvalrole.domain;

public enum ApprovalRoleDirectoryFailureCode {
    INVALID_QUERY, ROLE_NOT_FOUND, ROLE_INACTIVE, ORGANIZATION_INACTIVE,
    DIRECTORY_SOURCE_CONFLICT, REVISION_INCONSISTENT, INCOMPLETE_RESULT,
    HASH_UNPROVABLE, ASSIGNMENT_OVERLAP, DUPLICATE_ASSIGNMENT, CONCURRENT_MODIFICATION
}
