package cn.gov.enterprise.modules.workflow.domain.role;

import java.util.Comparator;
import java.util.List;

/** Non-persistent Candidate Pool draft generated by the prepared ROLE adapter. */
public record RoleCandidateResult(
        String roleCode, String organizationId, long revision,
        List<RoleCandidateUser> candidateUsers, String directoryHash,
        String resolverContractHash, String candidateHash,
        CandidateSource source, CandidateResolutionMode mode) {
    public RoleCandidateResult {
        roleCode = RoleDirectoryQuery.stableCode(roleCode, "roleCode");
        organizationId = RoleDirectoryQuery.required(organizationId, "organizationId", 100);
        if (revision <= 0) throw new IllegalArgumentException("revision must be positive");
        candidateUsers = List.copyOf(candidateUsers).stream()
                .sorted(Comparator.comparing(RoleCandidateUser::userId)).toList();
        if (candidateUsers.isEmpty()) throw new IllegalArgumentException("candidateUsers must not be empty");
        if (candidateUsers.stream().map(RoleCandidateUser::userId).distinct().count()
                != candidateUsers.size()) {
            throw new IllegalArgumentException("candidateUsers must be unique");
        }
        directoryHash = hash(directoryHash, "directoryHash");
        resolverContractHash = hash(resolverContractHash, "resolverContractHash");
        candidateHash = hash(candidateHash, "candidateHash");
        if (source == null) throw new IllegalArgumentException("source must not be null");
        if (mode == null) throw new IllegalArgumentException("mode must not be null");
    }

    static String hash(String value, String field) {
        String normalized = RoleDirectoryQuery.required(value, field, 64);
        if (!normalized.matches("[0-9a-f]{64}")) {
            throw new IllegalArgumentException(field + " must be lowercase SHA-256");
        }
        return normalized;
    }

    public boolean hasValidCandidateHash() {
        return candidateHash.equals(RoleCandidateCanonical.hash(this));
    }
}
