package cn.gov.enterprise.modules.workflow.domain.role;

/** Stable fail-closed errors defined by ROLE_DIRECTORY_PORT_V1. */
public enum RoleDirectoryErrorCode {
    ROLE_NOT_FOUND,
    ROLE_DISABLED,
    ROLE_ORG_MISMATCH,
    BUSINESS_ORG_INACTIVE,
    NO_ROLE_MEMBER,
    DIRECTORY_TIMEOUT,
    DIRECTORY_UNAVAILABLE,
    DIRECTORY_PARTIAL_RESULT,
    DIRECTORY_REVISION_MISMATCH,
    DIRECTORY_SOURCE_CONFLICT,
    CANDIDATE_LIMIT_EXCEEDED,
    DIRECTORY_CONTRACT_MISMATCH,
    INVALID_DIRECTORY_QUERY
}
