package cn.gov.enterprise.modules.workflow.domain.role.eligibility;

public enum RealtimeEligibilityFailureCode {
    ROLE_RUNTIME_DISABLED(Category.SYSTEM_INDETERMINATE),
    NOT_CANDIDATE(Category.BUSINESS_REJECT),
    TASK_NOT_FOUND(Category.BUSINESS_REJECT),
    TASK_NOT_CLAIMABLE(Category.BUSINESS_REJECT),
    CANDIDATE_POOL_NOT_FOUND(Category.BUSINESS_REJECT),
    CANDIDATE_POOL_MISMATCH(Category.BUSINESS_REJECT),
    CANDIDATE_MEMBER_INACTIVE(Category.BUSINESS_REJECT),
    ROLE_MEMBERSHIP_LOST(Category.BUSINESS_REJECT),
    USER_INACTIVE(Category.BUSINESS_REJECT),
    ORG_MEMBERSHIP_LOST(Category.BUSINESS_REJECT),
    DIRECTORY_UNAVAILABLE(Category.SYSTEM_INDETERMINATE),
    DIRECTORY_PARTIAL(Category.SYSTEM_INDETERMINATE),
    DIRECTORY_CONFLICT(Category.SYSTEM_INDETERMINATE),
    REVISION_INVALID(Category.SYSTEM_INDETERMINATE),
    DATASCOPE_DENIED(Category.BUSINESS_REJECT),
    DATASCOPE_UNAVAILABLE(Category.SYSTEM_INDETERMINATE),
    PLATFORM_SOD_DENIED(Category.BUSINESS_REJECT),
    BUSINESS_SOD_DENIED(Category.BUSINESS_REJECT),
    FEATURE_DISABLED(Category.BUSINESS_REJECT),
    CANARY_DENIED(Category.BUSINESS_REJECT),
    KILL_SWITCH_ACTIVE(Category.BUSINESS_REJECT),
    EVIDENCE_EXPIRED(Category.SYSTEM_INDETERMINATE),
    BINDING_MISMATCH(Category.SYSTEM_INDETERMINATE),
    HASH_MISMATCH(Category.SYSTEM_INDETERMINATE),
    ENTERPRISE_MISMATCH(Category.SYSTEM_INDETERMINATE),
    ACTIVE_CLAIM_EXISTS(Category.BUSINESS_REJECT),
    ASSIGNEE_MISMATCH(Category.BUSINESS_REJECT),
    IDEMPOTENCY_CONFLICT(Category.BUSINESS_REJECT),
    AUDIT_UNAVAILABLE(Category.SYSTEM_INDETERMINATE),
    CAPABILITY_UNAVAILABLE(Category.SYSTEM_INDETERMINATE);

    public enum Category { BUSINESS_REJECT, SYSTEM_INDETERMINATE }

    private final Category category;

    RealtimeEligibilityFailureCode(Category category) { this.category = category; }

    public Category category() { return category; }
}
