package cn.gov.enterprise.modules.workflow.infrastructure.directory.readiness;

public enum RoleDirectoryIntegrationBlockReason {
    ENVIRONMENT_MISMATCH,
    ENDPOINT_IDENTITY_MISMATCH,
    PROVIDER_MISMATCH,
    SECRET_PROVIDER_MISSING,
    TLS_CAPABILITY_MISSING,
    TRANSPORT_CONFIGURATION_INVALID,
    CONTRACT_MISMATCH,
    CANONICAL_MISMATCH,
    REVISION_CAPABILITY_UNSUPPORTED,
    HISTORICAL_QUERY_UNSUPPORTED,
    COMPLETE_SEMANTICS_UNSUPPORTED,
    PAGINATION_INCOMPLETE,
    CANDIDATE_LIMIT_UNGOVERNED,
    SLA_PLAN_MISSING,
    CIRCUIT_NOT_CLOSED,
    FAKE_ADAPTER_FORBIDDEN,
    PRODUCTION_ADAPTER_NOT_UNIQUE,
    OWNERSHIP_MISSING,
    RACI_APPROVAL_MISSING,
    SECURITY_REQUIREMENT_MISSING,
    METRICS_CAPABILITY_MISSING,
    AUDIT_CAPABILITY_MISSING,
    PII_POLICY_MISSING,
    PRODUCTION_DEPENDENCY_VIOLATION
}
