-- TEST/PREPROD-only disposable fixture. Never scanned by Flyway.
INSERT INTO workflow_definition(id,definition_code,definition_name,business_type,enterprise_id,owner_org_id,status,current_version_id,created_by,updated_by,deleted,delete_token,version)
VALUES(880000,'WF_AUDIT_FINAL','Audit E2E','ACCEPTANCE',880,880,'DRAFT',NULL,'acceptance','acceptance',0,0,0);
INSERT INTO workflow_version(id,definition_id,version_no,status,schema_version,engine_mode,content_hash_algorithm,content_hash,effective_from,published_by,published_time,created_by,updated_by,deleted,delete_token,version)
VALUES(880001,880000,1,'PUBLISHED','2.0','MULTI_NODE_LINEAR_V1','GRAPH_V2_SHA256',REPEAT('1',64),NOW(3),880,NOW(3),'acceptance','acceptance',0,0,0);
INSERT INTO workflow_node(id,version_id,node_code,node_name,node_type,node_order,governance_node_type,approval_mode,assignment_rule_type,assignment_rule_config,withdraw_allowed,enabled,created_by,updated_by,deleted,delete_token,version)
VALUES(880011,880001,'AUDIT_NODE','Audit Node','APPROVAL',1,'GENERAL_APPROVAL','SINGLE','USER','{"userId":881}',0,1,'acceptance','acceptance',0,0,0);
UPDATE workflow_definition SET status='ACTIVE',current_version_id=880001,version=1 WHERE id=880000;
INSERT INTO workflow_instance(id,instance_no,definition_id,version_id,definition_code_snapshot,definition_version_no,definition_content_hash_snapshot,resolver_code,resolver_version,resolver_contract_hash,business_type,business_id,business_key,enterprise_id,attempt_no,initiator_user_id,initiator_org_id,current_node_id,engine_mode,content_hash_algorithm_snapshot,current_node_execution_id,status,idempotency_key,request_hash,event_sequence,trace_id,started_time,created_by,updated_by,deleted,delete_token,version)
VALUES(880020,'WFI-AUDIT',880000,880001,'WF_AUDIT_FINAL',1,REPEAT('1',64),'EXPLICIT_USER','EXPLICIT_USER_V1','3166103d7697a6f2e46932214b0447310c69d6b624f6d92a282e9ef3ab496853','ACCEPTANCE','880020','ACCEPTANCE:880020',880,1,880,880,880011,'MULTI_NODE_LINEAR_V1','GRAPH_V2_SHA256',NULL,'RUNNING','fixture-audit',REPEAT('2',64),0,'trace-audit',NOW(3),'acceptance','acceptance',0,0,0);
INSERT INTO workflow_instance_resolver_binding_set(id,instance_id,definition_id,definition_version_id,manifest_version,manifest_hash,binding_count,binding_status,frozen_time,audit_info,created_by,updated_by,deleted,delete_token,version)
VALUES(880030,880020,880000,880001,'MULTI_RESOLVER_V1',REPEAT('3',64),1,'FROZEN',NOW(3),'acceptance','acceptance','acceptance',0,0,0);
INSERT INTO workflow_instance_resolver_binding(id,binding_set_id,instance_id,definition_version_id,resolver_code,resolver_version,strategy_type,resolver_mode,contract_hash,rule_hash,binding_status,frozen_time,audit_info,created_by,updated_by,deleted,delete_token,version)
VALUES(880031,880030,880020,880001,'ROLE_RESOLVER','ROLE_V1','ROLE','CANDIDATE_POOL',REPEAT('a',64),REPEAT('b',64),'FROZEN',NOW(3),'acceptance','acceptance','acceptance',0,0,0);
INSERT INTO workflow_node_resolver_binding_snapshot(id,binding_set_id,resolver_binding_id,instance_id,definition_version_id,node_id,node_code_snapshot,strategy_type,resolver_mode,target_type,target_value_snapshot,rule_version,rule_snapshot,rule_hash,node_binding_hash,binding_status,frozen_time,audit_info,created_by,updated_by,deleted,delete_token,version)
VALUES(880041,880030,880031,880020,880001,880011,'AUDIT_NODE','ROLE','CANDIDATE_POOL','ROLE','{"roleCode":"APPROVER"}','RULE_V1','{"roleCode":"APPROVER"}',REPEAT('b',64),REPEAT('c',64),'FROZEN',NOW(3),'acceptance','acceptance','acceptance',0,0,0);
INSERT INTO workflow_node_execution(id,execution_no,instance_id,version_id,node_id,node_code_snapshot,node_name_snapshot,visit_no,status,entered_time,activated_time,trace_id,created_by,updated_by,deleted,delete_token,version)
VALUES(880051,'WFNE-AUDIT',880020,880001,880011,'AUDIT_NODE','Audit Node',1,'ACTIVE',NOW(3),NOW(3),'trace-audit','acceptance','acceptance',0,0,0);
INSERT INTO workflow_task(id,task_no,instance_id,version_id,node_id,node_execution_id,node_code_snapshot,node_name_snapshot,task_round,participant_key,assignee_user_id,candidate_snapshot,assignment_mode,status,allowed_actions,created_by,updated_by,deleted,delete_token,version)
VALUES(880061,'WFT-AUDIT',880020,880001,880011,880051,'AUDIT_NODE','Audit Node',1,'AUDIT_NODE:1',NULL,'{}','CANDIDATE_POOL','PENDING','APPROVE,REJECT','acceptance','acceptance',0,0,0);
INSERT INTO workflow_task_assignment_snapshot(id,task_id,instance_id,version_id,node_id,node_execution_id,strategy_type,target_type,target_snapshot,resolved_users,resolved_user_count,resolve_time,audit_info,trace_id,created_by,updated_by,deleted,delete_token,version)
VALUES(880071,880061,880020,880001,880011,880051,'ROLE','ROLE','{}','[881]',1,NOW(3),'acceptance','trace-audit','acceptance','acceptance',0,0,0);
INSERT INTO workflow_task_candidate_pool(id,pool_no,task_id,instance_id,version_id,node_id,node_execution_id,binding_set_id,resolver_binding_id,node_resolver_binding_id,assignment_snapshot_id,assignment_mode,strategy_type,resolver_code,resolver_version,contract_hash,rule_hash,candidate_count,generated_time,effective_time,expires_time,pool_hash,status,audit_info,created_by,created_time,updated_by,updated_time,deleted,delete_token,remark,version)
VALUES(880081,'WCP-AUDIT',880061,880020,880001,880011,880051,880030,880031,880041,880071,'CANDIDATE_POOL','ROLE','ROLE_RESOLVER','ROLE_V1',REPEAT('a',64),REPEAT('b',64),1,NOW(3),NOW(3),DATE_ADD(NOW(3),INTERVAL 1 DAY),REPEAT('d',64),'AVAILABLE','acceptance','acceptance',NOW(3),'acceptance',NOW(3),0,0,NULL,0);
INSERT INTO workflow_task_candidate_member(id,pool_id,task_id,instance_id,candidate_user_id,source_type,source_ref_snapshot,org_id_snapshot,position_id_snapshot,role_id_snapshot,eligibility_snapshot,eligibility_hash,sort_order,generated_time,status,audit_info,created_by,created_time,updated_by,updated_time,deleted,delete_token,remark,version)
VALUES(880091,880081,880061,880020,881,'ROLE','ROLE:APPROVER',880,NULL,8801,'{"enabled":true}',REPEAT('e',64),1,NOW(3),'INCLUDED','acceptance','acceptance',NOW(3),'acceptance',NOW(3),0,0,NULL,0);
UPDATE workflow_task SET assignee_user_id=881,status='CLAIMED',claimed_time=NOW(3),version=1 WHERE id=880061;
INSERT INTO workflow_task_claim(id,claim_no,task_id,candidate_pool_id,candidate_member_id,instance_id,node_execution_id,candidate_user_id,operator_user_id,status,claim_time,eligibility_snapshot_hash,realtime_eligibility_result,data_scope_result,sod_result,rbac_result,task_status_before,task_status_after,pool_status_before,pool_status_after,task_version_before,task_version_after,idempotency_key,trace_id,created_by,updated_by,deleted,delete_token,version)
VALUES(880101,'WCL-AUDIT',880061,880081,880091,880020,880051,881,881,'CLAIMED',NOW(3),REPEAT('e',64),'ELIGIBLE','ALLOW:SCOPED','BASIC:V1:ALLOW','ALLOW:workflow:approve','PENDING','CLAIMED','AVAILABLE','CLAIMED',0,1,'idem-audit','trace-audit','acceptance','acceptance',0,0,0);
UPDATE workflow_task_candidate_pool SET status='CLAIMED',version=1 WHERE id=880081;
INSERT INTO workflow_task_claim_audit(id,event_no,task_id,candidate_pool_id,claim_id,candidate_member_id,instance_id,node_execution_id,operator_user_id,claimant_user_id,event_type,result,reason_code,frozen_eligibility_hash,realtime_eligibility_result,rbac_result,data_scope_result,sod_result,task_status_before,task_status_after,pool_status_before,pool_status_after,event_time,trace_id,idempotency_key,event_hash,created_by,updated_by,deleted,delete_token,version)
VALUES(880111,'WCLA-AUDIT',880061,880081,880101,880091,880020,880051,881,881,'CLAIM','SUCCESS','CLAIMED',REPEAT('e',64),'ELIGIBLE','ALLOW:workflow:approve','ALLOW:SCOPED','BASIC:V1:ALLOW','PENDING','CLAIMED','AVAILABLE','CLAIMED',NOW(3),'trace-audit','idem-audit',REPEAT('a',64),'acceptance','acceptance',0,0,0);
