package cn.gov.enterprise.modules.workflow.infrastructure.directory.connectivity;

public enum RoleDirectoryConnectivityBlockReason {
    UNSUPPORTED_ENVIRONMENT, ENDPOINT_IDENTITY_MISMATCH, PROVIDER_IDENTITY_MISMATCH,
    ENVIRONMENT_IDENTITY_MISMATCH, SECRET_SOURCE_INVALID, TLS_INVALID, AUTHENTICATION_FAILED,
    CONTRACT_MISMATCH, CANONICAL_MISMATCH, REVISION_CAPABILITY_MISSING,
    HISTORICAL_CAPABILITY_MISSING, COMPLETE_SEMANTICS_MISSING, PAGINATION_SEMANTICS_MISSING,
    TIMEOUT_POLICY_INVALID, RETRY_POLICY_INVALID, CIRCUIT_NOT_CLOSED,
    FAKE_ADAPTER_LEAK, PRODUCTION_ADAPTER_NOT_UNIQUE, STARTUP_GATE_FAILED,
    PRODUCTION_ISOLATION_VIOLATION, BUSINESS_QUERY_ISOLATION_VIOLATION
}
