-- Enterprise Platform - system base schema
-- Target: MySQL 8.x
-- Charset: utf8mb4
-- IDs are generated by the application (snowflake), not AUTO_INCREMENT.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS sys_org (
    id BIGINT NOT NULL COMMENT '主键',
    parent_id BIGINT NULL COMMENT '上级组织ID',
    org_code VARCHAR(64) NOT NULL COMMENT '组织编码',
    org_name VARCHAR(128) NOT NULL COMMENT '组织名称',
    org_short_name VARCHAR(64) NULL COMMENT '组织简称',
    org_type VARCHAR(32) NOT NULL COMMENT '组织类型',
    tree_path VARCHAR(1000) NOT NULL DEFAULT '/' COMMENT '组织树祖先路径',
    tree_level INT NOT NULL DEFAULT 1 COMMENT '组织树层级',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    leader_user_id BIGINT NULL COMMENT '负责人用户ID，逻辑引用',
    contact_phone VARCHAR(32) NULL COMMENT '联系电话',
    established_date DATE NULL COMMENT '成立日期',
    status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_org_code (org_code),
    KEY idx_sys_org_parent_sort (parent_id, deleted, sort_no),
    KEY idx_sys_org_path (tree_path(255)),
    KEY idx_sys_org_type_status (org_type, status),
    CONSTRAINT fk_sys_org_parent FOREIGN KEY (parent_id) REFERENCES sys_org (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='统一组织表';

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT NOT NULL COMMENT '主键',
    role_code VARCHAR(64) NOT NULL COMMENT '角色编码',
    role_name VARCHAR(128) NOT NULL COMMENT '角色名称',
    data_scope_type VARCHAR(32) NOT NULL DEFAULT 'SELF' COMMENT '数据范围类型',
    role_category VARCHAR(32) NOT NULL DEFAULT 'BUSINESS' COMMENT '角色分类：SYSTEM/BUSINESS',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常',
    remark VARCHAR(500) NULL COMMENT '备注',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_role_code (role_code),
    KEY idx_sys_role_status_sort (status, deleted, sort_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT NOT NULL COMMENT '主键',
    permission_code VARCHAR(128) NOT NULL COMMENT '权限编码',
    permission_name VARCHAR(128) NOT NULL COMMENT '权限名称',
    permission_type VARCHAR(32) NOT NULL COMMENT '权限类型：API/BUTTON/DATA',
    resource_path VARCHAR(500) NULL COMMENT '资源路径或表达式',
    http_method VARCHAR(16) NULL COMMENT 'HTTP方法',
    module_code VARCHAR(64) NOT NULL COMMENT '模块编码',
    status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常',
    remark VARCHAR(500) NULL COMMENT '备注',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_permission_code (permission_code),
    KEY idx_sys_permission_module (module_code, status, deleted),
    KEY idx_sys_permission_resource (resource_path(255), http_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='权限资源表';

CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT NOT NULL COMMENT '主键',
    parent_id BIGINT NULL COMMENT '上级菜单ID',
    permission_id BIGINT NULL COMMENT '绑定权限ID',
    menu_name VARCHAR(128) NOT NULL COMMENT '菜单名称',
    menu_type VARCHAR(16) NOT NULL COMMENT '类型：DIRECTORY/MENU/BUTTON/EXTERNAL',
    route_name VARCHAR(128) NULL COMMENT '前端路由名称',
    route_path VARCHAR(255) NULL COMMENT '前端路由路径',
    component_path VARCHAR(255) NULL COMMENT '组件路径',
    redirect_path VARCHAR(255) NULL COMMENT '重定向路径',
    icon VARCHAR(64) NULL COMMENT '图标编码',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    visible SMALLINT NOT NULL DEFAULT 1 COMMENT '是否可见：0否，1是',
    keep_alive SMALLINT NOT NULL DEFAULT 0 COMMENT '是否缓存：0否，1是',
    status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    KEY idx_sys_menu_parent_sort (parent_id, deleted, status, sort_no),
    KEY idx_sys_menu_permission (permission_id),
    KEY idx_sys_menu_route_name (route_name),
    CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id) REFERENCES sys_menu (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_sys_menu_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
        ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单表';

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL COMMENT '主键',
    org_id BIGINT NOT NULL COMMENT '所属主组织ID',
    username VARCHAR(64) NOT NULL COMMENT '登录用户名',
    password_hash VARCHAR(255) NOT NULL COMMENT '密码摘要',
    employee_no VARCHAR(64) NULL COMMENT '人员主数据编码',
    real_name VARCHAR(64) NOT NULL COMMENT '姓名',
    mobile VARCHAR(32) NULL COMMENT '手机号码',
    email VARCHAR(128) NULL COMMENT '电子邮箱',
    avatar_url VARCHAR(500) NULL COMMENT '头像地址',
    status SMALLINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1正常，2锁定',
    login_fail_count INT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
    locked_until DATETIME(3) NULL COMMENT '锁定截止时间',
    last_login_time DATETIME(3) NULL COMMENT '最近成功登录时间',
    last_login_ip VARCHAR(64) NULL COMMENT '最近登录IP',
    password_changed_time DATETIME(3) NULL COMMENT '密码修改时间',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_username (username),
    UNIQUE KEY uk_sys_user_employee_no (employee_no),
    KEY idx_sys_user_org_status (org_id, status, deleted),
    KEY idx_sys_user_mobile (mobile),
    KEY idx_sys_user_real_name (real_name),
    CONSTRAINT fk_sys_user_org FOREIGN KEY (org_id) REFERENCES sys_org (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户账号表';

CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (user_id, role_id),
    KEY idx_sys_user_role_role (role_id, deleted),
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user (id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色关联表';

CREATE TABLE IF NOT EXISTS sys_role_permission (
    role_id BIGINT NOT NULL COMMENT '角色ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (role_id, permission_id),
    KEY idx_sys_role_permission_permission (permission_id, deleted),
    CONSTRAINT fk_sys_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色权限关联表';

CREATE TABLE IF NOT EXISTS sys_role_menu (
    role_id BIGINT NOT NULL COMMENT '角色ID',
    menu_id BIGINT NOT NULL COMMENT '菜单ID',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (role_id, menu_id),
    KEY idx_sys_role_menu_menu (menu_id, deleted),
    CONSTRAINT fk_sys_role_menu_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_menu_menu FOREIGN KEY (menu_id) REFERENCES sys_menu (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色菜单关联表';

CREATE TABLE IF NOT EXISTS sys_role_org (
    role_id BIGINT NOT NULL COMMENT '角色ID',
    org_id BIGINT NOT NULL COMMENT '组织ID',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (role_id, org_id),
    KEY idx_sys_role_org_org (org_id, deleted),
    CONSTRAINT fk_sys_role_org_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_org_org FOREIGN KEY (org_id) REFERENCES sys_org (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色自定义组织数据范围表';

CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT NOT NULL COMMENT '主键',
    log_type VARCHAR(32) NOT NULL COMMENT '日志类型：LOGIN/OPERATION/SECURITY',
    user_id BIGINT NULL COMMENT '操作用户ID',
    org_id BIGINT NULL COMMENT '操作组织ID',
    username VARCHAR(64) NULL COMMENT '用户名快照',
    module_code VARCHAR(64) NULL COMMENT '模块编码',
    operation_type VARCHAR(32) NULL COMMENT '操作类型',
    operation_desc VARCHAR(255) NULL COMMENT '操作说明',
    request_method VARCHAR(16) NULL COMMENT 'HTTP方法',
    request_uri VARCHAR(500) NULL COMMENT '请求URI',
    ip_address VARCHAR(64) NULL COMMENT '客户端IP',
    user_agent VARCHAR(500) NULL COMMENT '客户端标识',
    trace_id VARCHAR(64) NULL COMMENT '链路追踪ID',
    result_status SMALLINT NOT NULL DEFAULT 1 COMMENT '执行结果：0失败，1成功',
    error_code VARCHAR(64) NULL COMMENT '错误码',
    error_message VARCHAR(1000) NULL COMMENT '脱敏错误摘要',
    duration_ms BIGINT NULL COMMENT '执行耗时毫秒',
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    created_by BIGINT NULL COMMENT '创建人',
    updated_by BIGINT NULL COMMENT '更新人',
    deleted SMALLINT NOT NULL DEFAULT 0 COMMENT '删除标识：0正常，1删除',
    PRIMARY KEY (id),
    KEY idx_sys_log_created_type (created_time, log_type),
    KEY idx_sys_log_user_time (user_id, created_time),
    KEY idx_sys_log_org_time (org_id, created_time),
    KEY idx_sys_log_trace (trace_id),
    KEY idx_sys_log_result_time (result_status, created_time),
    CONSTRAINT fk_sys_log_user FOREIGN KEY (user_id) REFERENCES sys_user (id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_sys_log_org FOREIGN KEY (org_id) REFERENCES sys_org (id)
        ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='统一审计日志表';

SET FOREIGN_KEY_CHECKS = 1;

-- Initial system role. No default user/password is stored in source control.
INSERT INTO sys_role (
    id, role_code, role_name, data_scope_type, role_category,
    sort_no, status, remark, created_time, updated_time, deleted
) VALUES (
    1, 'SUPER_ADMIN', '超级管理员', 'ALL', 'SYSTEM',
    1, 1, '系统内置角色', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0
) ON DUPLICATE KEY UPDATE
    role_name = VALUES(role_name),
    updated_time = CURRENT_TIMESTAMP(3);

INSERT INTO sys_permission (
    id, permission_code, permission_name, permission_type,
    resource_path, http_method, module_code, status,
    created_time, updated_time, deleted
) VALUES
    (1001, 'system:user:manage', '用户管理', 'API', '/system/users/**', NULL, 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (1002, 'system:role:manage', '角色管理', 'API', '/system/roles/**', NULL, 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (1003, 'system:org:manage', '组织管理', 'API', '/system/orgs/**', NULL, 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (1004, 'system:permission:manage', '权限管理', 'API', '/system/permissions/**', NULL, 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (1005, 'system:menu:manage', '菜单管理', 'API', '/system/menus/**', NULL, 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (1006, 'system:log:list', '日志查询', 'API', '/system/logs/**', 'GET', 'system', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0)
ON DUPLICATE KEY UPDATE
    permission_name = VALUES(permission_name),
    resource_path = VALUES(resource_path),
    http_method = VALUES(http_method),
    updated_time = CURRENT_TIMESTAMP(3);

INSERT INTO sys_menu (
    id, parent_id, permission_id, menu_name, menu_type,
    route_name, route_path, component_path, icon, sort_no,
    visible, keep_alive, status, created_time, updated_time, deleted
) VALUES
    (100, NULL, NULL, '系统管理', 'DIRECTORY', 'System', '/system', NULL, 'Setting', 100, 1, 0, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (110, 100, 1001, '用户管理', 'MENU', 'SystemUser', '/system/users', 'system/user/index', 'User', 10, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (120, 100, 1002, '角色管理', 'MENU', 'SystemRole', '/system/roles', 'system/role/index', 'Avatar', 20, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (130, 100, 1003, '组织管理', 'MENU', 'SystemOrg', '/system/orgs', 'system/org/index', 'OfficeBuilding', 30, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (140, 100, 1004, '权限管理', 'MENU', 'SystemPermission', '/system/permissions', 'system/permission/index', 'Lock', 40, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (150, 100, 1005, '菜单管理', 'MENU', 'SystemMenu', '/system/menus', 'system/menu/index', 'Menu', 50, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
    (160, 100, 1006, '日志管理', 'MENU', 'SystemLog', '/system/logs', 'system/log/index', 'Document', 60, 1, 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0)
ON DUPLICATE KEY UPDATE
    menu_name = VALUES(menu_name),
    permission_id = VALUES(permission_id),
    route_path = VALUES(route_path),
    component_path = VALUES(component_path),
    sort_no = VALUES(sort_no),
    updated_time = CURRENT_TIMESTAMP(3);

INSERT INTO sys_role_permission (
    role_id, permission_id, created_time, updated_time, deleted
)
SELECT 1, p.id, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0
FROM sys_permission p
WHERE p.id BETWEEN 1001 AND 1006
ON DUPLICATE KEY UPDATE
    deleted = 0,
    updated_time = CURRENT_TIMESTAMP(3);

INSERT INTO sys_role_menu (
    role_id, menu_id, created_time, updated_time, deleted
)
SELECT 1, m.id, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0
FROM sys_menu m
WHERE m.id IN (100, 110, 120, 130, 140, 150, 160)
ON DUPLICATE KEY UPDATE
    deleted = 0,
    updated_time = CURRENT_TIMESTAMP(3);
