param([string]$OutputRoot="D:\codex-validation-v2620-$((Get-Date).ToString('yyyyMMdd-HHmmss'))",[int]$BasePort=37920)
$ErrorActionPreference='Stop'
$workspace=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$mysqlHome='C:\Program Files\MySQL\MySQL Server 8.4';$mysqld=Join-Path $mysqlHome 'bin\mysqld.exe';$mysql=Join-Path $mysqlHome 'bin\mysql.exe';$admin=Join-Path $mysqlHome 'bin\mysqladmin.exe'
$flyway='C:\Users\WUKONG\AppData\Local\Temp\enterprise-v246-acceptance-68bf692b16d34ee191946695ae0bef9b\flyway-fresh\flyway-13.0.0\flyway.cmd'
$migrationRoot=Join-Path $workspace 'database\migration\mysql';$baselineSource=Join-Path $workspace 'database\mysql';$baselineRoot=Join-Path $OutputRoot baseline;$full=Join-Path $OutputRoot full;$previous=Join-Path $OutputRoot previous;$evidence=Join-Path $OutputRoot evidence
$baselineFiles=@('01_database.sql','02_sys.sql','03_hr.sql','04_party.sql','05_project.sql','06_operation.sql','07_investment.sql','08_data_asset.sql','09_risk.sql','10_init_data.sql','11_sprint_1_user_permissions.sql','12_sprint_1_org_permissions.sql','13_sprint_1_role_permissions.sql','14_sprint_1_rbac_acceptance.sql','15_sprint_1_menu_center.sql','16_sprint_1_log_center.sql','V1.1.0__investment_data_risk_bi.sql')
if(Test-Path $OutputRoot){throw "Disposable root exists: $OutputRoot"};if(!$OutputRoot.StartsWith('D:\codex-validation-v2620-')){throw 'Unsafe output root'}
New-Item -ItemType Directory $full,$previous,$evidence,$baselineRoot -Force|Out-Null;Get-ChildItem $migrationRoot -Filter 'V*.sql'|Copy-Item -Destination $full;Get-ChildItem $migrationRoot -Filter 'V*.sql'|Where-Object Name -ne 'V2.6.20__create_approval_role_directory_provider_audit.sql'|Copy-Item -Destination $previous;foreach($asset in $baselineFiles){Copy-Item (Join-Path $baselineSource $asset) (Join-Path $baselineRoot $asset)}
$servers=@();$checks=[ordered]@{};$failures=[Collections.Generic.List[string]]::new()
function Start-Db($name,$port){$root=Join-Path $OutputRoot $name;$data=Join-Path $root data;New-Item -ItemType Directory $data -Force|Out-Null;$ini=Join-Path $root my.ini;[IO.File]::WriteAllText($ini,@"
[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=$($data.Replace('\','/'))
port=$port
bind-address=127.0.0.1
mysqlx=0
skip-log-bin
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
log-error=$((Join-Path $root 'mysql.err').Replace('\','/'))
pid-file=$((Join-Path $root 'mysql.pid').Replace('\','/'))
secure-file-priv=""
"@,[Text.UTF8Encoding]::new($false));&$mysqld "--defaults-file=$ini" --initialize-insecure;if($LASTEXITCODE){throw 'mysql initialize failed'};$process=Start-Process $mysqld -ArgumentList "--defaults-file=$ini" -WindowStyle Hidden -PassThru;$script:servers+=@(@{Port=$port;Process=$process;Ini=$ini});for($i=0;$i-lt100;$i++){&$admin --protocol=TCP --host=127.0.0.1 --port=$port --user=root ping 2>$null|Out-Null;if(!$LASTEXITCODE){return @{Name=$name;Port=$port;Process=$process;Ini=$ini}};Start-Sleep -Milliseconds 300};throw 'mysql not ready'}
function Invoke-Sql($server,[string]$sql,[switch]$Raw){$args=@('--protocol=TCP','--host=127.0.0.1',"--port=$($server.Port)",'--user=root','--database=enterprise_platform');if($Raw){$args+=@('--batch','--raw','--skip-column-names')};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=&$mysql @args "--execute=$sql" 2>&1;$code=$LASTEXITCODE;$ErrorActionPreference=$old;@{Code=$code;Output=($out-join"`n")}}
function Initialize-Baseline($server){foreach($name in $baselineFiles){$file=Join-Path $baselineRoot $name;$args=@('--protocol=TCP','--host=127.0.0.1',"--port=$($server.Port)",'--user=root','--default-character-set=utf8mb4');if($name-ne'01_database.sql'){$args+='--database=enterprise_platform'};&$mysql @args "--execute=source $($file.Replace('\','/'))"|Out-Null;if($LASTEXITCODE){throw "baseline failed: $name"}}}
function Invoke-Flyway($server,$location,$command,$target=''){$args=@("-url=jdbc:mysql://127.0.0.1:$($server.Port)/enterprise_platform",'-user=root','-password=',"-locations=filesystem:$($location.Replace('\','/'))",'-baselineOnMigrate=true','-baselineVersion=2.0.0','-validateMigrationNaming=true','-cleanDisabled=true');if($target){$args+="-target=$target"};$out=&$flyway @args $command 2>&1;$out|Set-Content (Join-Path $evidence "$($server.Name)-$command-$([DateTime]::UtcNow.Ticks).log");if($LASTEXITCODE){throw ($out-join"`n")};$out-join"`n"}
function Schema-Fingerprint($server){$columns=(Invoke-Sql $server "SELECT CONCAT(table_name,'|',column_name,'|',column_type,'|',is_nullable,'|',IFNULL(column_default,'<NULL>'),'|',IFNULL(collation_name,'<NULL>')) FROM information_schema.columns WHERE table_schema=DATABASE() ORDER BY table_name,ordinal_position" -Raw).Output;$indexes=(Invoke-Sql $server "SELECT CONCAT(table_name,'|',index_name,'|',non_unique,'|',seq_in_index,'|',column_name) FROM information_schema.statistics WHERE table_schema=DATABASE() ORDER BY table_name,index_name,seq_in_index" -Raw).Output;$triggers=(Invoke-Sql $server "SELECT CONCAT(trigger_name,'|',event_manipulation,'|',event_object_table,'|',action_timing,'|',action_statement) FROM information_schema.triggers WHERE trigger_schema=DATABASE() ORDER BY trigger_name" -Raw).Output;$file=Join-Path $evidence "$($server.Name)-schema.txt";[IO.File]::WriteAllText($file,$columns+"`n"+$indexes+"`n"+$triggers,[Text.UTF8Encoding]::new($false));(Get-FileHash $file -Algorithm SHA256).Hash.ToLower()}
function Set-Check($name,[bool]$pass,$proof=''){$script:checks[$name]=$pass;if(!$pass){$script:failures.Add("$name :: $proof")}}
function Insert-Sql($id,$event,$request,$evidenceHash,$outcome='SUCCESS',$failure='NULL',$revision='1',$result="REPEAT('b',64)",$count='2',$environment='TEST'){return "INSERT INTO approval_role_directory_provider_audit(audit_id,audit_event_id,correlation_id,request_id,provider_code,provider_version,service_identity,environment_identity,caller_service_identity,enterprise_id,organization_id,role_code,effective_at,contract_version,contract_hash,canonical_version,directory_revision,directory_result_hash,candidate_count,outcome,failure_code,request_hash,evidence_hash,started_at,completed_at) VALUES('$id','$event','C-$id','$request','ORG_GOV_APPROVAL_ROLE_DIRECTORY','1.0.0','provider','$environment','workflow','E','O','ROLE_A','2026-08-21','ROLE_DIRECTORY_PORT_V1',REPEAT('a',64),'ROLE_CANONICAL_JSON_V1',$revision,$result,$count,'$outcome',$failure,REPEAT('c',64),'$evidenceHash','2026-08-21','2026-08-21 00:00:00.001')"}
function Reject($server,$name,$sql,$expected=''){$result=Invoke-Sql $server $sql;Set-Check $name ($result.Code-ne0-and(!$expected-or$result.Output.Contains($expected))) $result.Output}
try{
  $fresh=Start-Db fresh ($BasePort+1);$upgrade=Start-Db upgrade ($BasePort+2);Initialize-Baseline $fresh;Initialize-Baseline $upgrade
  $null=Invoke-Flyway $fresh $full migrate;$null=Invoke-Flyway $fresh $full validate;$freshNoop=Invoke-Flyway $fresh $full migrate
  $null=Invoke-Flyway $upgrade $previous migrate '2.6.19';$before=[int](Invoke-Sql $upgrade 'SELECT COUNT(*) FROM flyway_schema_history WHERE success=1' -Raw).Output.Trim();$null=Invoke-Flyway $upgrade $full migrate;$null=Invoke-Flyway $upgrade $full validate;$upgradeNoop=Invoke-Flyway $upgrade $full migrate;$after=[int](Invoke-Sql $upgrade 'SELECT COUNT(*) FROM flyway_schema_history WHERE success=1' -Raw).Output.Trim()
  $freshFp=Schema-Fingerprint $fresh;$upgradeFp=Schema-Fingerprint $upgrade;Set-Check FRESH_UPGRADE_FINGERPRINT ($freshFp-eq$upgradeFp) "$freshFp/$upgradeFp";Set-Check UPGRADE_ONLY_V2620 (($after-$before)-eq1) "$before->$after";Set-Check FRESH_NOOP ($freshNoop-match'No migration necessary') $freshNoop;Set-Check UPGRADE_NOOP ($upgradeNoop-match'No migration necessary') $upgradeNoop
  $checksum=(Invoke-Sql $fresh "SELECT checksum FROM flyway_schema_history WHERE version='2.6.20'" -Raw).Output.Trim();$sha=(Get-FileHash (Join-Path $migrationRoot 'V2.6.20__create_approval_role_directory_provider_audit.sql') -Algorithm SHA256).Hash.ToLower()
  $legal=Invoke-Sql $fresh (Insert-Sql A1 EV1 REQ1 ('d'*64));Set-Check SUCCESS_INSERT ($legal.Code-eq0) $legal.Output
  Reject $fresh UPDATE_APPEND_ONLY "UPDATE approval_role_directory_provider_audit SET outcome='FAILED' WHERE audit_id='A1'" 'APPROVAL_ROLE_DIRECTORY_PROVIDER_AUDIT_APPEND_ONLY';Reject $fresh DELETE_APPEND_ONLY "DELETE FROM approval_role_directory_provider_audit WHERE audit_id='A1'" 'APPROVAL_ROLE_DIRECTORY_PROVIDER_AUDIT_APPEND_ONLY'
  Reject $fresh DUPLICATE_EVENT (Insert-Sql A2 EV1 REQ2 ('e'*64));Reject $fresh DUPLICATE_EVIDENCE (Insert-Sql A3 EV3 REQ3 ('d'*64));Reject $fresh UPPERCASE_HASH (Insert-Sql A4 EV4 REQ4 ('D'*64));Reject $fresh INVALID_ENVIRONMENT (Insert-Sql A5 EV5 REQ5 ('5'*64) SUCCESS NULL 1 "REPEAT('b',64)" 1 DEV);Reject $fresh MISSING_SUCCESS_FACTS (Insert-Sql A6 EV6 REQ6 ('6'*64) SUCCESS NULL NULL NULL NULL);Reject $fresh INVALID_OUTCOME (Insert-Sql A7 EV7 REQ7 ('7'*64) UNKNOWN);Reject $fresh NEGATIVE_COUNT (Insert-Sql A8 EV8 REQ8 ('8'*64) SUCCESS NULL 1 "REPEAT('b',64)" -1)
  $rejected=Invoke-Sql $fresh (Insert-Sql AR1 EVR1 REQR1 ('9'*64) REJECTED "'INVALID_ROLE'" NULL NULL NULL);Set-Check REJECTED_INSERT ($rejected.Code-eq0) $rejected.Output;$failed=Invoke-Sql $fresh (Insert-Sql AF1 EVF1 REQF1 ('0'*64) FAILED "'DB_DEPENDENCY_FAILURE'" NULL NULL NULL);Set-Check FAILED_INSERT ($failed.Code-eq0) $failed.Output
  foreach($concurrency in 10,25,50){$jobs=@();for($i=1;$i-le$concurrency;$i++){$id="C$concurrency-$i";$hash=('{0:x64}' -f ($concurrency*1000+$i));$sql=Insert-Sql $id "E-$id" "R-$id" $hash;$jobs+=Start-Job -ScriptBlock {param($exe,$port,$statement)&$exe --protocol=TCP --host=127.0.0.1 --port=$port --user=root --database=enterprise_platform "--execute=$statement"} -ArgumentList $mysql,$fresh.Port,$sql};$jobs|Wait-Job|Out-Null;$jobErrors=@($jobs|Where-Object State -ne Completed).Count;$jobs|Receive-Job|Out-Null;$jobs|Remove-Job;$actual=[int](Invoke-Sql $fresh "SELECT COUNT(*) FROM approval_role_directory_provider_audit WHERE audit_id LIKE 'C$concurrency-%'" -Raw).Output.Trim();Set-Check "CONCURRENCY_$concurrency" ($actual-eq$concurrency-and$jobErrors-eq0) "rows=$actual jobs=$jobErrors"}
  $beforeRestart=(Invoke-Sql $fresh 'SELECT COUNT(*) FROM approval_role_directory_provider_audit' -Raw).Output.Trim();&$admin --protocol=TCP --host=127.0.0.1 --port=$($fresh.Port) --user=root shutdown|Out-Null;Wait-Process -Id $fresh.Process.Id -ErrorAction SilentlyContinue;$fresh.Process=Start-Process $mysqld -ArgumentList "--defaults-file=$($fresh.Ini)" -WindowStyle Hidden -PassThru;for($i=0;$i-lt100;$i++){&$admin --protocol=TCP --host=127.0.0.1 --port=$($fresh.Port) --user=root ping 2>$null|Out-Null;if(!$LASTEXITCODE){break};Start-Sleep -Milliseconds 300};$afterRestart=(Invoke-Sql $fresh 'SELECT COUNT(*) FROM approval_role_directory_provider_audit' -Raw).Output.Trim();Set-Check RESTART_RECOVERY ($beforeRestart-eq$afterRestart) "$beforeRestart/$afterRestart"
  $summary=[ordered]@{result=if($failures.Count){'FAIL'}else{'PASS'};output_root=$OutputRoot;mysql=(&$mysql --version);flyway=((&$flyway -v 2>&1)-join' ');sha256=$sha;flyway_checksum=$checksum;fresh_schema_fingerprint=$freshFp;upgrade_schema_fingerprint=$upgradeFp;checks=$checks;rows_after_restart=$afterRestart;failures=$failures};$summary|ConvertTo-Json -Depth 8|Tee-Object -FilePath (Join-Path $evidence summary.json);if($failures.Count){exit 2}
}finally{foreach($server in $servers){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$admin --protocol=TCP --host=127.0.0.1 --port=$server.Port --user=root shutdown 2>$null|Out-Null;$ErrorActionPreference=$old;if($server.Process-and!$server.Process.HasExited){Stop-Process -Id $server.Process.Id -Force -ErrorAction SilentlyContinue}}}
