param(
  [string]$OutputRoot="D:\codex-validation-org-dir-2-$((Get-Date).ToString('yyyyMMdd-HHmmss'))",
  [int]$BasePort=37610
)
$ErrorActionPreference='Stop'
$dbPort=$BasePort+1;$appPort=$BasePort+2
$workspace=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$backend=Join-Path $workspace 'backend';$jar=Join-Path $backend 'target\enterprise-platform.jar'
$mysqlHome='C:\Program Files\MySQL\MySQL Server 8.4';$mysqld=Join-Path $mysqlHome 'bin\mysqld.exe';$mysql=Join-Path $mysqlHome 'bin\mysql.exe';$mysqladmin=Join-Path $mysqlHome 'bin\mysqladmin.exe'
$flyway='C:\Users\WUKONG\AppData\Local\Temp\enterprise-v246-acceptance-68bf692b16d34ee191946695ae0bef9b\flyway-fresh\flyway-13.0.0\flyway.cmd'
$java='C:\Users\WUKONG\.codex\tmp\wf522-tools\jdk-21.0.12+8\bin\java.exe';$keytool='C:\Users\WUKONG\.codex\tmp\wf522-tools\jdk-21.0.12+8\bin\keytool.exe';$mvn='C:\Users\WUKONG\.codex\tmp\wf522-tools\apache-maven-3.9.9\bin\mvn.cmd'
$migrationRoot=Join-Path $workspace 'database\migration\mysql';$baselineRoot=Join-Path $workspace 'database\mysql'
$baselineFiles=@('01_database.sql','02_sys.sql','03_hr.sql','04_party.sql','05_project.sql','06_operation.sql','07_investment.sql','08_data_asset.sql','09_risk.sql','10_init_data.sql','11_sprint_1_user_permissions.sql','12_sprint_1_org_permissions.sql','13_sprint_1_role_permissions.sql','14_sprint_1_rbac_acceptance.sql','15_sprint_1_menu_center.sql','16_sprint_1_log_center.sql','V1.1.0__investment_data_risk_bi.sql')
foreach($a in @($mysqld,$mysql,$mysqladmin,$flyway,$java,$keytool,$mvn,$jar)){if(!(Test-Path -LiteralPath $a)){throw "Missing validation asset: $a"}}
if(Test-Path $OutputRoot){throw "Disposable root exists: $OutputRoot"};if(!$OutputRoot.StartsWith('D:\codex-validation-org-dir-2-')){throw 'Unsafe validation root'}
$evidence=Join-Path $OutputRoot evidence;$data=Join-Path $OutputRoot mysql-data;$logs=Join-Path $OutputRoot logs;$tls=Join-Path $OutputRoot tls;$baseline=Join-Path $OutputRoot baseline;New-Item -ItemType Directory $evidence,$data,$logs,$tls,$baseline -Force|Out-Null
foreach($n in $baselineFiles){Copy-Item (Join-Path $baselineRoot $n) (Join-Path $baseline $n)}
$checks=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[string]]::new();$server=$null;$app=$null
function Add($name,[bool]$pass,$proof=''){$checks.Add([ordered]@{name=$name;pass=$pass;proof=$proof});if(!$pass){$failures.Add("$name :: $proof")}}
function DB([string]$sql,[switch]$raw){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($BasePort+1)",'--user=root','--database=enterprise_platform');if($raw){$a+=@('--batch','--raw','--skip-column-names')};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=&$mysql @a "--execute=$sql" 2>&1;$c=$LASTEXITCODE;$ErrorActionPreference=$old;@{ExitCode=$c;Output=($o-join"`n")}}
function Curl([string]$path,[string]$method='GET',[string]$body='',[string]$token=$script:token,[string]$identity='workflow-role-directory-client',[switch]$NoCa,[switch]$Ip){$hostName=if($Ip){'127.0.0.1'}else{'localhost'};$url="https://${hostName}:$appPort/api/internal/approval-role-directory/$path";$args=@('--silent','--show-error','--output',(Join-Path $evidence 'curl-body.tmp'),'--write-out','%{http_code}');if(!$NoCa){$args+=@('--cacert',$script:caCert,'--ssl-no-revoke')};$args+=@('--header',"Authorization: Bearer $token",'--header',"X-Service-Identity: $identity");if($method-ne'GET'){$args+=@('--header','Content-Type: application/json','--request',$method,'--data',$body)};$args+=$url;$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$status=&curl.exe @args 2>(Join-Path $evidence 'curl-error.tmp');$exit=$LASTEXITCODE;$ErrorActionPreference=$old;$response=if(Test-Path (Join-Path $evidence 'curl-body.tmp')){Get-Content (Join-Path $evidence 'curl-body.tmp') -Raw}else{''};@{ExitCode=$exit;Status=$status;Body=$response}}
function Resolve($role,$at){$body=@{enterpriseId='TEST_ENTERPRISE';organizationId='990001';roleCode=$role;effectiveAt=$at;correlationId="org-dir-2-$role-$at"}|ConvertTo-Json -Compress;Curl resolve POST $body}
try{
  $ini=Join-Path $OutputRoot my.ini;[IO.File]::WriteAllText($ini,@"
[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=$($data.Replace('\','/'))
port=$($BasePort+1)
bind-address=127.0.0.1
mysqlx=0
skip-log-bin
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
log-error=$((Join-Path $logs 'mysql.err').Replace('\','/'))
pid-file=$((Join-Path $OutputRoot 'mysql.pid').Replace('\','/'))
secure-file-priv=""
"@,[Text.UTF8Encoding]::new($false));&$mysqld "--defaults-file=$ini" --initialize-insecure;if($LASTEXITCODE){throw 'mysql init failed'};$server=Start-Process $mysqld -ArgumentList "--defaults-file=$ini" -WindowStyle Hidden -PassThru
  foreach($i in 1..100){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 "--port=$dbPort" --user=root ping 2>$null|Out-Null;$c=$LASTEXITCODE;$ErrorActionPreference=$old;if(!$c){break};Start-Sleep -Milliseconds 300};if($c){throw 'mysql not ready'}
  foreach($n in $baselineFiles){$f=Join-Path $baseline $n;$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$dbPort",'--user=root','--default-character-set=utf8mb4');if($n-ne'01_database.sql'){$a+='--database=enterprise_platform'};$baselineOut=&$mysql @a "--execute=source $($f.Replace('\','/'))" 2>&1;$baselineCode=$LASTEXITCODE;if($baselineCode){throw "baseline failed $n :: $($baselineOut-join' ')"}}
  $fa=@("-url=jdbc:mysql://127.0.0.1:$dbPort/enterprise_platform",'-user=root','-password=',"-locations=filesystem:$($migrationRoot.Replace('\','/'))",'-baselineOnMigrate=true','-baselineVersion=2.0.0','-validateMigrationNaming=true','-cleanDisabled=true');&$flyway @fa migrate|Set-Content (Join-Path $evidence flyway-migrate.log);if($LASTEXITCODE){throw 'flyway migrate failed'};&$flyway @fa validate|Set-Content (Join-Path $evidence flyway-validate.log);if($LASTEXITCODE){throw 'flyway validate failed'};$noop=&$flyway @fa migrate 2>&1;Add FLYWAY_NOOP ((($noop-join"`n")-match'No migration necessary')) ($noop-join' ')
  $seed=Join-Path $evidence seed.sql;$lines=[Collections.Generic.List[string]]::new();$lines.Add("INSERT INTO sys_org(id,org_code,org_name,org_type,parent_id,tree_path,tree_level,status,create_by,update_by,deleted,delete_token,version) VALUES(990001,'TEST_ORG_A','TEST ORG A','DEPARTMENT',NULL,'/',1,1,'test','test',0,0,0),(990002,'TEST_ORG_B','TEST ORG B','DEPARTMENT',NULL,'/',1,1,'test','test',0,0,0);")
  $lines.Add("INSERT INTO sys_user(id,username,password,real_name,org_id,status,create_by,update_by,deleted,delete_token,version) VALUES(990101,'test-user-1','fixture','TEST USER 1',990001,1,'test','test',0,0,0),(990102,'test-user-2','fixture','TEST USER 2',990001,1,'test','test',0,0,0),(990103,'test-user-3','fixture','TEST USER 3',990001,1,'test','test',0,0,0);")
  $roles=@(@(992001,'TEST_APPROVER'),@(992002,'TEST_FINANCE_REVIEWER'),@(992003,'TEST_CONFLICT'),@(992101,'TEST_LOAD_1'),@(992102,'TEST_LOAD_10'),@(992103,'TEST_LOAD_50'),@(992104,'TEST_LOAD_100'),@(992105,'TEST_LOAD_500'))
  foreach($r in $roles){$lines.Add("INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by) VALUES($($r[0]),'TEST_ENTERPRISE','$($r[1])','$($r[1])','PROCESS_APPROVAL_ROLE','BUSINESS_ORG','ACTIVE','test','test');");$head=993000+[int]($r[0]-992000);$rev=994000+[int]($r[0]-992000);$lines.Add("INSERT INTO approval_role_revision_head(id,enterprise_id,organization_id,role_code,current_revision,current_result_hash,create_by,update_by) VALUES($head,'TEST_ENTERPRISE',990001,'$($r[1])',1,REPEAT('a',64),'test','test');");$lines.Add("INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,create_by,update_by) VALUES($rev,'TEST_ENTERPRISE',990001,'$($r[1])',1,REPEAT('a',64),'BATCH','fixture','2026-01-01','2026-01-01','test','test','test');")}
  function A($id,$roleId,$role,$user,$from,$to,$system,$ref){$t=if($to){"'$to'"}else{'NULL'};$lines.Add("INSERT INTO approval_role_assignment(id,enterprise_id,organization_id,role_id,role_code,user_id,effective_from,effective_to,status,source_type,source_system,source_reference,source_reference_hash,evidence_priority,recorded_at,assignment_key_hash,create_by,update_by) VALUES($id,'TEST_ENTERPRISE',990001,$roleId,'$role',$user,'$from',$t,'ACTIVE','GOVERNANCE_DECISION','$system','$ref',SHA2('$ref',256),1,'2026-01-01',SHA2('$id-$ref',256),'test','test');")}
  A 996001 992001 TEST_APPROVER 990101 '2026-01-01' '2026-06-01' GOV DEC-A;A 996002 992001 TEST_APPROVER 990102 '2026-06-01' '' GOV DEC-B;A 996003 992001 TEST_APPROVER 990101 '2026-01-01' '2026-06-01' HR HR-A
  A 996010 992003 TEST_CONFLICT 990101 '2026-01-01' '' GOV CONFLICT;A 996011 992003 TEST_CONFLICT 990102 '2026-01-01' '' GOV CONFLICT
  $nextUser=995001;$nextAssignment=997001;foreach($pair in @(@(992101,'TEST_LOAD_1',1),@(992102,'TEST_LOAD_10',10),@(992103,'TEST_LOAD_50',50),@(992104,'TEST_LOAD_100',100),@(992105,'TEST_LOAD_500',500))){for($i=1;$i-le$pair[2];$i++){$u=$nextUser++;$lines.Add("INSERT INTO sys_user(id,username,password,real_name,org_id,status,create_by,update_by) VALUES($u,'load-$u','fixture','LOAD USER',990001,1,'test','test');");A $nextAssignment $pair[0] $pair[1] $u '2026-01-01' '' LOAD "LOAD-$nextAssignment";$nextAssignment++}}
  [IO.File]::WriteAllLines($seed,$lines,[Text.UTF8Encoding]::new($false));&$mysql --protocol=TCP --host=127.0.0.1 "--port=$dbPort" --user=root --database=enterprise_platform "--execute=source $($seed.Replace('\','/'))" 2>&1|Set-Content (Join-Path $evidence seed.log);if($LASTEXITCODE){throw 'seed failed'}
  $pass='test-only-keystore-password';$ca=Join-Path $tls ca.p12;$script:caCert=Join-Path $tls ca.crt;$serverStore=Join-Path $tls provider.p12;$csr=Join-Path $tls provider.csr;$signed=Join-Path $tls provider.crt;$trust=Join-Path $tls trust.p12
  &$keytool -genkeypair -alias testca -dname 'CN=ORG-DIR-TEST-CA,O=Enterprise Test' -keyalg RSA -keysize 3072 -validity 30 -ext bc:c -keystore $ca -storetype PKCS12 -storepass $pass -keypass $pass -noprompt|Out-Null;&$keytool -exportcert -alias testca -keystore $ca -storepass $pass -rfc -file $caCert|Out-Null
  &$keytool -genkeypair -alias provider -dname 'CN=localhost,O=Enterprise Test' -keyalg RSA -keysize 3072 -validity 20 -ext SAN=dns:localhost -keystore $serverStore -storetype PKCS12 -storepass $pass -keypass $pass -noprompt|Out-Null;&$keytool -certreq -alias provider -keystore $serverStore -storepass $pass -file $csr -ext SAN=dns:localhost|Out-Null;&$keytool -gencert -alias testca -keystore $ca -storepass $pass -infile $csr -outfile $signed -rfc -validity 20 -ext KU=digitalSignature,keyEncipherment -ext EKU=serverAuth -ext SAN=dns:localhost|Out-Null;&$keytool -importcert -alias testca -file $caCert -keystore $serverStore -storepass $pass -noprompt|Out-Null;&$keytool -importcert -alias provider -file $signed -keystore $serverStore -storepass $pass -noprompt|Out-Null;&$keytool -importcert -alias testca -file $caCert -keystore $trust -storetype PKCS12 -storepass $pass -noprompt|Out-Null
  $script:token=([Guid]::NewGuid().ToString('N')+[Guid]::NewGuid().ToString('N'));$env:APPROVAL_ROLE_DIRECTORY_PROVIDER_ENABLED='true';$env:APPROVAL_ROLE_DIRECTORY_ENVIRONMENT='TEST';$env:APPROVAL_ROLE_DIRECTORY_SERVICE_TOKEN=$token;$env:APPROVAL_ROLE_DIRECTORY_CLIENT_IDENTITY='workflow-role-directory-client';$env:DB_URL="jdbc:mysql://127.0.0.1:$dbPort/enterprise_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false";$env:DB_USERNAME='root';$env:DB_PASSWORD='';$env:DB_MAPPING_CHECK_ENABLED='false';$env:JWT_SECRET='test-only-jwt-secret-at-least-thirty-two-characters';$env:SERVER_PORT=$appPort.ToString();$env:SERVER_SSL_ENABLED='true';$env:SERVER_SSL_KEY_STORE=$serverStore;$env:SERVER_SSL_KEY_STORE_PASSWORD=$pass;$env:SERVER_SSL_KEY_STORE_TYPE='PKCS12';$env:SERVER_SSL_KEY_ALIAS='provider'
  $app=Start-Process $java -ArgumentList @('-jar',$jar) -WorkingDirectory $backend -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $logs app.out) -RedirectStandardError (Join-Path $logs app.err)
  $ready=$false;foreach($i in 1..120){Start-Sleep -Milliseconds 500;$h=Curl health;if($h.ExitCode-eq0-and$h.Status-eq'200'){$ready=$true;break};if($app.HasExited){break}};Add PROVIDER_AVAILABLE $ready "https://localhost:$($BasePort+2)";if(!$ready){throw 'provider not ready'}
  $missing=Curl health -token '';Add AUTH_MISSING ($missing.Status-eq'401') $missing.Status;$invalid=Curl health -token 'invalid-token-that-is-long-enough-but-wrong';Add AUTH_INVALID ($invalid.Status-eq'401') $invalid.Status;$wrong=Curl health -token $token -identity 'wrong-service';Add AUTH_WRONG_IDENTITY ($wrong.Status-eq'403') $wrong.Status
  $untrusted=Curl health -NoCa;Add TLS_UNTRUSTED_REJECTED ($untrusted.ExitCode-ne0) $untrusted.ExitCode;$wrongHost=Curl health -Ip;Add TLS_HOSTNAME_REJECTED ($wrongHost.ExitCode-ne0) $wrongHost.ExitCode
  $meta=(Curl metadata).Body|ConvertFrom-Json;Add METADATA_IDENTITY ($meta.providerCode-eq'ORG_GOV_APPROVAL_ROLE_DIRECTORY'-and$meta.environmentIdentity-eq'TEST'-and$meta.contractVersion-eq'ROLE_DIRECTORY_PORT_V1'-and$meta.canonicalVersion-eq'ROLE_CANONICAL_JSON_V1') "$($meta.providerCode)/$($meta.environmentIdentity)"
  $canonical=(Curl canonical/verify POST (@{expectedHash=$meta.canonicalVectorHash}|ConvertTo-Json -Compress)).Body|ConvertFrom-Json;Add CANONICAL_CROSS_VALIDATION ($canonical.matches-and$canonical.vectorHash-eq$meta.canonicalVectorHash) $canonical.vectorHash
  $r1=(Resolve TEST_APPROVER '2026-05-31T12:00:00Z').Body|ConvertFrom-Json;$u1=@($r1.members|Select-Object -Expand userId -Unique);Add HISTORICAL_U1 ($u1.Count-eq1-and$u1[0]-eq'990101'-and$r1.members.Count-eq2) "revision=$($r1.revision) users=$($u1-join',') evidence=$($r1.members.Count)"
  $boundary=(Resolve TEST_APPROVER '2026-06-01T00:00:00Z').Body|ConvertFrom-Json;$u2=@($boundary.members|Select-Object -Expand userId -Unique);Add HANDOVER_BOUNDARY ($u2.Count-eq1-and$u2[0]-eq'990102') ($u2-join',')
  $zero=(Resolve TEST_FINANCE_REVIEWER '2026-05-31T12:00:00Z');$z=$zero.Body|ConvertFrom-Json;Add ZERO_COMPLETE ($zero.Status-eq'200'-and$z.complete-and$z.members.Count-eq0) $zero.Body
  $conflict=Resolve TEST_CONFLICT '2026-05-31T12:00:00Z';Add SOURCE_CONFLICT ($conflict.Status-eq'422'-and$conflict.Body-match'DIRECTORY_SOURCE_CONFLICT') $conflict.Body
  $r=DB "INSERT INTO approval_role_assignment(id,enterprise_id,organization_id,role_id,role_code,user_id,effective_from,status,source_type,source_system,source_reference,source_reference_hash,evidence_priority,recorded_at,assignment_key_hash,create_by,update_by) VALUES(996020,'TEST_ENTERPRISE',990001,992001,'TEST_APPROVER',990103,'2026-07-01','ACTIVE','GOVERNANCE_DECISION','GOV','DEC-C',SHA2('DEC-C',256),1,'2026-07-01',SHA2('996020-DEC-C',256),'test','test');INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by) VALUES(994020,'TEST_ENTERPRISE',990001,'TEST_APPROVER',2,SHA2('r2',256),'ASSIGN','r2','2026-07-01','2026-07-01','test',1,REPEAT('a',64),'test','test');UPDATE approval_role_revision_head SET current_revision=2,current_result_hash=SHA2('r2',256),version=1,update_by='test' WHERE enterprise_id='TEST_ENTERPRISE' AND organization_id=990001 AND role_code='TEST_APPROVER'";if($r.ExitCode){throw $r.Output};$r2=(Resolve TEST_APPROVER '2026-07-01T00:00:00Z').Body|ConvertFrom-Json;Add REVISION_R2 ($r2.revision-eq2-and$r2.resultHash-ne$r1.resultHash) "R$($r2.revision)/$($r2.resultHash)"
  $r=DB "UPDATE approval_role_assignment SET status='CORRECTED',update_by='test',version=1 WHERE id=996001;INSERT INTO approval_role_assignment(id,enterprise_id,organization_id,role_id,role_code,user_id,effective_from,effective_to,status,source_type,source_system,source_reference,source_reference_hash,evidence_priority,recorded_at,assignment_key_hash,create_by,update_by) VALUES(996021,'TEST_ENTERPRISE',990001,992001,'TEST_APPROVER',990103,'2026-01-01','2026-06-01','ACTIVE','GOVERNANCE_DECISION','GOV','DEC-A-CORRECTED',SHA2('DEC-A-CORRECTED',256),1,'2026-08-01',SHA2('996021-DEC-A-CORRECTED',256),'test','test');INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,affected_from,correction_reference,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by) VALUES(994021,'TEST_ENTERPRISE',990001,'TEST_APPROVER',3,SHA2('r3',256),'CORRECTION','correct fixture','2026-01-01','2026-01-01','CORR-1','2026-08-01','test',2,SHA2('r2',256),'test','test');UPDATE approval_role_revision_head SET current_revision=3,current_result_hash=SHA2('r3',256),version=2,update_by='test' WHERE enterprise_id='TEST_ENTERPRISE' AND organization_id=990001 AND role_code='TEST_APPROVER'";if($r.ExitCode){throw $r.Output};$r3=(Resolve TEST_APPROVER '2026-05-31T12:00:00Z').Body|ConvertFrom-Json;Add CORRECTION_R3 ($r3.revision-eq3-and$r3.resultHash-ne$r1.resultHash) "R$($r3.revision)/$($r3.resultHash)"
  $loadEvidence=Join-Path $evidence load-sla.json;$env:JAVA_HOME='C:\Users\WUKONG\.codex\tmp\wf522-tools\jdk-21.0.12+8';$args=@('-q','-Dtest=ApprovalRoleDirectoryRealConnectivityTest',"-Dorg.dir.real.base=https://localhost:$($BasePort+2)/api/internal/approval-role-directory","-Dorg.dir.real.identity=workflow-role-directory-client","-Dorg.dir.real.token=$token","-Dorg.dir.real.truststore=$trust","-Dorg.dir.real.trustpass=$pass","-Dorg.dir.real.evidence=$loadEvidence",'test');$testOut=&$mvn @args 2>&1;$testCode=$LASTEXITCODE;$testOut|Set-Content (Join-Path $evidence production-adapter-test.log);Add PRODUCTION_ADAPTER_REAL ($testCode-eq0) "exit=$testCode"
  if(Test-Path $loadEvidence){$sla=Get-Content $loadEvidence -Raw|ConvertFrom-Json;Add SLA_LOAD_COLLECTED ($sla.aggregate.requests-eq60-and$sla.aggregate.success_rate-eq1) "requests=$($sla.aggregate.requests) p95=$($sla.aggregate.p95_ms)ms payload=$($sla.aggregate.average_payload_bytes)"}else{Add SLA_LOAD_COLLECTED $false 'missing evidence'}
  $auditCounts=(DB "SELECT CONCAT(COUNT(*),'|',SUM(outcome='SUCCESS'),'|',SUM(outcome='REJECTED'),'|',SUM(outcome='FAILED')) FROM approval_role_directory_provider_audit" -raw).Output.Trim().Split('|');Add PERSISTENT_PROVIDER_AUDIT (($auditCounts.Count-eq4)-and([int]$auditCounts[0]-eq161)-and([int]$auditCounts[1]-eq156)-and([int]$auditCounts[2]-eq5)-and([int]$auditCounts[3]-eq0)) ($auditCounts-join'/')
  $invalidHashes=(DB "SELECT COUNT(*) FROM approval_role_directory_provider_audit WHERE request_hash NOT REGEXP '^[0-9a-f]{64}$' OR evidence_hash NOT REGEXP '^[0-9a-f]{64}$' OR contract_hash NOT REGEXP '^[0-9a-f]{64}$' OR (directory_result_hash IS NOT NULL AND directory_result_hash NOT REGEXP '^[0-9a-f]{64}$')" -raw).Output.Trim();Add PROVIDER_AUDIT_HASHES ($invalidHashes-eq'0') $invalidHashes
  $successProof=(DB "SELECT CONCAT(directory_revision,'|',directory_result_hash,'|',candidate_count,'|',contract_hash,'|',outcome) FROM approval_role_directory_provider_audit WHERE correlation_id='org-dir-2-TEST_APPROVER-2026-05-31T12:00:00Z' ORDER BY created_at LIMIT 1" -raw).Output.Trim().Split('|');Add SUCCESS_AUDIT_FACTS (($successProof.Count-eq5)-and$successProof[0]-eq$r1.revision.ToString()-and$successProof[1]-eq$r1.resultHash-and$successProof[2]-eq'1'-and$successProof[3]-eq$r1.contractHash-and$successProof[4]-eq'SUCCESS') ($successProof-join'/')
  $piiColumns=(DB "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='approval_role_directory_provider_audit' AND column_name REGEXP '(member|username|real_name|phone|id_card|address|salary|token|secret|credential|authorization)'" -raw).Output.Trim();Add PROVIDER_AUDIT_PII_MINIMIZED ($piiColumns-eq'0') $piiColumns
  $history=(DB "SELECT version,checksum,success FROM flyway_schema_history ORDER BY installed_rank" -raw).Output;$history|Set-Content (Join-Path $evidence flyway-history.txt);$sha=(Get-FileHash (Join-Path $migrationRoot 'V2.6.17__create_approval_role_directory.sql') -Algorithm SHA256).Hash.ToLower()
  $r=DB "CREATE TRIGGER trg_test_provider_audit_insert_failure BEFORE INSERT ON approval_role_directory_provider_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=1644,MESSAGE_TEXT='TEST_AUDIT_INSERT_FAILURE'";if($r.ExitCode){throw $r.Output};$insertFailure=Resolve TEST_APPROVER '2026-05-31T12:00:00Z';Add AUDIT_INSERT_FAILURE_FAIL_CLOSED ($insertFailure.Status-eq'503'-and$insertFailure.Body-match'PROVIDER_AUDIT_PERSISTENCE_FAILED') "$($insertFailure.Status)/$($insertFailure.Body)";$r=DB "DROP TRIGGER trg_test_provider_audit_insert_failure";if($r.ExitCode){throw $r.Output}
  &$mysqladmin --protocol=TCP --host=127.0.0.1 "--port=$dbPort" --user=root shutdown|Out-Null;Start-Sleep -Seconds 1;$connectionFailure=Resolve TEST_APPROVER '2026-05-31T12:00:00Z';Add AUDIT_CONNECTION_FAILURE_FAIL_CLOSED (($connectionFailure.Status-in @('500','503'))-and$connectionFailure.Body-notmatch'resultHash|members') "$($connectionFailure.Status)/$($connectionFailure.Body)"
  $summary=[ordered]@{result=if($failures.Count){'FAIL'}else{'PASS'};outputRoot=$OutputRoot;environment='TEST';endpoint="https://localhost:$($BasePort+2)/api/internal/approval-role-directory";mysql=(&$mysql --version);flyway=((&$flyway -v 2>&1)-join' ');tls='TLSv1.3 TEST_ONLY_CA hostname verification enabled';v2617Sha256=$sha;checks=$checks;failures=$failures};$summary|ConvertTo-Json -Depth 8|Set-Content (Join-Path $evidence summary.json);$summary|ConvertTo-Json -Depth 8;if($failures.Count){exit 2}
}finally{
  foreach($name in @('APPROVAL_ROLE_DIRECTORY_PROVIDER_ENABLED','APPROVAL_ROLE_DIRECTORY_ENVIRONMENT','APPROVAL_ROLE_DIRECTORY_SERVICE_TOKEN','APPROVAL_ROLE_DIRECTORY_CLIENT_IDENTITY','DB_URL','DB_USERNAME','DB_PASSWORD','DB_MAPPING_CHECK_ENABLED','JWT_SECRET','SERVER_PORT','SERVER_SSL_ENABLED','SERVER_SSL_KEY_STORE','SERVER_SSL_KEY_STORE_PASSWORD','SERVER_SSL_KEY_STORE_TYPE','SERVER_SSL_KEY_ALIAS')){Remove-Item "Env:$name" -ErrorAction SilentlyContinue}
  if($app-and!$app.HasExited){Stop-Process -Id $app.Id -Force -ErrorAction SilentlyContinue};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 "--port=$dbPort" --user=root shutdown 2>$null|Out-Null;$ErrorActionPreference=$old;if($server-and!$server.HasExited){Stop-Process -Id $server.Id -Force -ErrorAction SilentlyContinue}
}
