param([string]$OutputRoot="D:\codex-validation-wf-audit-final-$((Get-Date).ToString('yyyyMMdd-HHmmss'))",[int]$BasePort=37190)
$ErrorActionPreference='Stop'
$workspace=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$mysqlHome='C:\Program Files\MySQL\MySQL Server 8.4';$mysqld=Join-Path $mysqlHome 'bin\mysqld.exe';$mysql=Join-Path $mysqlHome 'bin\mysql.exe';$mysqladmin=Join-Path $mysqlHome 'bin\mysqladmin.exe'
$flyway='C:\Users\WUKONG\AppData\Local\Temp\enterprise-v246-acceptance-68bf692b16d34ee191946695ae0bef9b\flyway-fresh\flyway-13.0.0\flyway.cmd'
$migrationRoot=Join-Path $workspace 'database\migration\mysql';$baselineRoot=Join-Path $workspace 'database\mysql';$fpSql=Join-Path $baselineRoot 'verification\schema_fingerprint.sql'
$baselineFiles=@('01_database.sql','02_sys.sql','03_hr.sql','04_party.sql','05_project.sql','06_operation.sql','07_investment.sql','08_data_asset.sql','09_risk.sql','10_init_data.sql','11_sprint_1_user_permissions.sql','12_sprint_1_org_permissions.sql','13_sprint_1_role_permissions.sql','14_sprint_1_rbac_acceptance.sql','15_sprint_1_menu_center.sql','16_sprint_1_log_center.sql','V1.1.0__investment_data_risk_bi.sql')
if(Test-Path $OutputRoot){throw "Disposable root exists: $OutputRoot"};if(!$OutputRoot.StartsWith('D:\codex-validation-wf-audit-final-')){throw 'Unsafe output root'}
$evidence=Join-Path $OutputRoot evidence;$full=Join-Path $OutputRoot full;$upgradePath=Join-Path $OutputRoot to2618;$baseline=Join-Path $OutputRoot baseline
New-Item -ItemType Directory -Path $evidence,$full,$upgradePath,$baseline -Force|Out-Null
Get-ChildItem $migrationRoot -Filter 'V*.sql' -File|Copy-Item -Destination $full
Get-ChildItem $migrationRoot -Filter 'V*.sql' -File|Where-Object Name -ne 'V2.6.19__create_governance_external_audit_sink.sql'|Copy-Item -Destination $upgradePath
foreach($n in $baselineFiles){Copy-Item (Join-Path $baselineRoot $n) (Join-Path $baseline $n)}
$servers=@();$checks=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[string]]::new()
function Add($n,[bool]$ok,$proof=''){$checks.Add([ordered]@{name=$n;pass=$ok;proof=$proof});if(!$ok){$failures.Add("$n :: $proof")}}
function New-Server($name,$port){$root=Join-Path $OutputRoot $name;$data=Join-Path $root data;$logs=Join-Path $root logs;New-Item -ItemType Directory $data,$logs -Force|Out-Null;$ini=Join-Path $root my.ini;[IO.File]::WriteAllText($ini,@"
[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=$($data.Replace('\','/'))
port=$port
bind-address=127.0.0.1
mysqlx=0
skip-log-bin
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
log-error=$((Join-Path $logs 'mysql.err').Replace('\','/'))
pid-file=$((Join-Path $root 'mysql.pid').Replace('\','/'))
secure-file-priv=""
"@,[Text.UTF8Encoding]::new($false));&$mysqld "--defaults-file=$ini" --initialize-insecure;if($LASTEXITCODE){throw "init failed"};$p=Start-Process $mysqld -ArgumentList "--defaults-file=$ini" -WindowStyle Hidden -PassThru;$script:servers+=$p;foreach($i in 1..100){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 --port=$port --user=root ping 2>$null|Out-Null;$c=$LASTEXITCODE;$ErrorActionPreference=$old;if(!$c){return @{Name=$name;Port=$port}};Start-Sleep -Milliseconds 300};throw 'mysql not ready'}
function DB($s,$sql,[switch]$raw){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--database=enterprise_platform');if($raw){$a+=@('--batch','--raw','--skip-column-names')};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=&$mysql @a "--execute=$sql" 2>&1;$c=$LASTEXITCODE;$ErrorActionPreference=$old;@{ExitCode=$c;Output=($o-join"`n")}}
function Baseline($s){foreach($n in $baselineFiles){$f=Join-Path $baseline $n;$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--default-character-set=utf8mb4');if($n-ne'01_database.sql'){$a+='--database=enterprise_platform'};&$mysql @a "--execute=source $($f.Replace('\','/'))"|Out-Null;if($LASTEXITCODE){throw "baseline failed $n"}}}
function Fly($s,$loc,$command,$target=''){$a=@("-url=jdbc:mysql://127.0.0.1:$($s.Port)/enterprise_platform",'-user=root','-password=',"-locations=filesystem:$($loc.Replace('\','/'))",'-baselineOnMigrate=true','-baselineVersion=2.0.0','-validateMigrationNaming=true','-cleanDisabled=true');if($target){$a+="-target=$target"};$a+=$command;$o=&$flyway @a 2>&1;$o|Set-Content (Join-Path $evidence "$($s.Name)-$command-$([DateTime]::UtcNow.Ticks).log");if($LASTEXITCODE){throw ($o-join"`n")};($o-join"`n")}
function Reject($s,$name,$sql,$expected=''){$r=DB $s $sql;$ok=$r.ExitCode-ne0-and(!$expected-or$r.Output.Contains($expected));Add $name $ok $r.Output}
function FP($s){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--database=enterprise_platform','--batch','--raw','--skip-column-names');$rows=Get-Content $fpSql -Raw|&$mysql @a;$tr=&$mysql @a '--execute=SELECT CONCAT("TRIGGER|",trigger_name,"|",event_manipulation,"|",event_object_table,"|",action_timing,"|",REPLACE(REPLACE(action_statement,CHAR(13)," "),CHAR(10)," ")) FROM information_schema.triggers WHERE trigger_schema=DATABASE() ORDER BY trigger_name';$all=@($rows)+@($tr);$audit=$all|Where-Object{$_-match'governance_external_audit|workflow_role_external_audit'};$o=@{};foreach($p in @(@('full',$all),@('audit',$audit))){$f=Join-Path $evidence "$($s.Name)-$($p[0]).txt";[IO.File]::WriteAllText($f,(($p[1]-join"`n")+"`n"),[Text.UTF8Encoding]::new($false));$o[$p[0]]=(Get-FileHash $f -Algorithm SHA256).Hash.ToLower()};$o}
try{
 $fresh=New-Server fresh ($BasePort+1);$upgrade=New-Server upgrade ($BasePort+2);Baseline $fresh;Baseline $upgrade
 $null=Fly $fresh $full migrate;$null=Fly $fresh $full validate;$noop=Fly $fresh $full migrate;Add FRESH $true;Add FRESH_NOOP ($noop-match'No migration necessary') $noop
 $null=Fly $upgrade $upgradePath migrate '2.6.18';$before=[int](DB $upgrade "SELECT COUNT(*) FROM flyway_schema_history WHERE success=1" -raw).Output.Trim();$null=Fly $upgrade $full migrate;$null=Fly $upgrade $full validate;$noop2=Fly $upgrade $full migrate;$after=[int](DB $upgrade "SELECT COUNT(*) FROM flyway_schema_history WHERE success=1" -raw).Output.Trim();Add UPGRADE_ONLY_V2619 (($after-$before)-eq1) "$before->$after";Add UPGRADE_NOOP ($noop2-match'No migration necessary') $noop2
 $ff=FP $fresh;$uf=FP $upgrade;Add FINGERPRINT_FULL ($ff.full-eq$uf.full) "$($ff.full)/$($uf.full)";Add FINGERPRINT_AUDIT ($ff.audit-eq$uf.audit) "$($ff.audit)/$($uf.audit)"
 $checksum=(DB $fresh "SELECT checksum FROM flyway_schema_history WHERE version='2.6.19' AND success=1" -raw).Output.Trim()
 $tables=(DB $fresh "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('governance_external_audit_event','governance_external_audit_receipt','workflow_role_external_audit_payload')" -raw).Output.Trim();Add TABLES ($tables-eq'3') $tables
 $triggers=(DB $fresh "SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND event_object_table IN ('governance_external_audit_event','governance_external_audit_receipt','workflow_role_external_audit_payload')" -raw).Output.Trim();Add TRIGGERS ($triggers-eq'6') $triggers
 $event="INSERT INTO governance_external_audit_event VALUES('E1','ROLE_TASK_CLAIMED','1','2026-08-21','1','2','3','4','5','6','7','A','8','R',REPEAT('a',64),REPEAT('b',64),REPEAT('c',64),REPEAT('d',64),'C',REPEAT('e',64),JSON_OBJECT('auditEventId','E1','payloadHash',REPEAT('e',64)),'2026-08-21')";$r=DB $fresh $event;Add EVENT_INSERT ($r.ExitCode-eq0) $r.Output
 $receipt="INSERT INTO governance_external_audit_receipt VALUES('R1','E1','GOVERNANCE_AUDIT_SINK','1.0.0','2026-08-21',REPEAT('e',64),'ACCEPTED',REPEAT('f',64))";$r=DB $fresh $receipt;Add RECEIPT_INSERT ($r.ExitCode-eq0) $r.Output
 Reject $fresh EVENT_DUPLICATE $event;Reject $fresh EVENT_UPDATE "UPDATE governance_external_audit_event SET correlation_id='X' WHERE audit_event_id='E1'" 'GOVERNANCE_AUDIT_EVENT_APPEND_ONLY';Reject $fresh EVENT_DELETE "DELETE FROM governance_external_audit_event WHERE audit_event_id='E1'" 'GOVERNANCE_AUDIT_EVENT_APPEND_ONLY'
 Reject $fresh RECEIPT_ORPHAN "INSERT INTO governance_external_audit_receipt VALUES('R2','MISSING','P','1','2026-08-21',REPEAT('a',64),'ACCEPTED',REPEAT('b',64))";Reject $fresh RECEIPT_UPDATE "UPDATE governance_external_audit_receipt SET provider_version='2' WHERE external_receipt_id='R1'" 'GOVERNANCE_AUDIT_RECEIPT_APPEND_ONLY';Reject $fresh RECEIPT_DELETE "DELETE FROM governance_external_audit_receipt WHERE external_receipt_id='R1'" 'GOVERNANCE_AUDIT_RECEIPT_APPEND_ONLY'
 Reject $fresh BAD_HASH "INSERT INTO governance_external_audit_event VALUES('E2','T','1','2026-08-21','1','2','3','4','5','6','7','A','8','R',REPEAT('A',64),REPEAT('b',64),REPEAT('c',64),REPEAT('d',64),'C',REPEAT('e',64),JSON_OBJECT('auditEventId','E2','payloadHash',REPEAT('e',64)),'2026-08-21')"
 Reject $fresh JSON_IDENTITY_MISMATCH "INSERT INTO governance_external_audit_event VALUES('E3','T','1','2026-08-21','1','2','3','4','5','6','7','A','8','R',REPEAT('a',64),REPEAT('b',64),REPEAT('c',64),REPEAT('d',64),'C',REPEAT('1',64),JSON_OBJECT('auditEventId','WRONG','payloadHash',REPEAT('1',64)),'2026-08-21')"
 $history=(DB $fresh "SELECT installed_rank,version,description,checksum,success FROM flyway_schema_history ORDER BY installed_rank" -raw).Output;$history|Set-Content (Join-Path $evidence history.txt)
 $summary=[ordered]@{result=if($failures.Count){'FAIL'}else{'PASS'};outputRoot=$OutputRoot;mysql=(&$mysql --version);flyway=((&$flyway -v 2>&1)-join' ');sha256=(Get-FileHash (Join-Path $migrationRoot 'V2.6.19__create_governance_external_audit_sink.sql') -Algorithm SHA256).Hash.ToLower();flywayChecksum=$checksum;freshFingerprint=$ff;upgradeFingerprint=$uf;checks=$checks;failures=$failures};$summary|ConvertTo-Json -Depth 8|Set-Content (Join-Path $evidence summary.json);$summary|ConvertTo-Json -Depth 8;if($failures.Count){exit 2}
}finally{foreach($s in @($fresh,$upgrade)){if($null-ne$s){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 --port=$s.Port --user=root shutdown 2>$null|Out-Null;$ErrorActionPreference=$old}};foreach($p in $servers){if(!$p.HasExited){Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue}}}
