[CmdletBinding()]
param(
    [string]$OutputRoot = "D:\codex-rc2-v2624-$((Get-Date).ToString('yyyyMMdd-HHmmss'))",
    [int]$FreshAPort = 38341,
    [int]$FreshBPort = 38342,
    [int]$UpgradePort = 38343,
    [string]$MySqlHome = 'C:\Program Files\MySQL\MySQL Server 8.4',
    [string]$FlywayPath = 'C:\Users\WUKONG\AppData\Local\Temp\enterprise-v246-acceptance-68bf692b16d34ee191946695ae0bef9b\flyway-fresh\flyway-13.0.0\flyway.cmd',
    [string]$JavaHome = 'C:\Users\WUKONG\.cache\codex-java21-maven\jdk-fresh\jdk-21.0.12+8',
    [string]$MavenPath = 'C:\Users\WUKONG\.cache\codex-java21-maven\maven\apache-maven-3.9.9\bin\mvn.cmd'
)

$ErrorActionPreference='Stop'
$workspace=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$baselineSource=Join-Path $workspace 'database\mysql'
$migrationSource=Join-Path $workspace 'database\migration\mysql'
$manifest=Join-Path $migrationSource 'SHA256SUMS'
$output=[IO.Path]::GetFullPath($OutputRoot)
$evidence=Join-Path $output 'evidence'
$baselineCopy=Join-Path $output 'baseline'
$fullCopy=Join-Path $output 'migration-full'
$upgradeCopy=Join-Path $output 'migration-v2623'
$mysqld=Join-Path $MySqlHome 'bin\mysqld.exe'
$mysql=Join-Path $MySqlHome 'bin\mysql.exe'
$mysqladmin=Join-Path $MySqlHome 'bin\mysqladmin.exe'
$expectedSha='e549147abcf77168a1b1ef465c76ed642f7ce02f250117d0019bbeeb8d524822'
$baselineFiles=@('01_database.sql','02_sys.sql','03_hr.sql','04_party.sql','05_project.sql','06_operation.sql','07_investment.sql','08_data_asset.sql','09_risk.sql','10_init_data.sql','11_sprint_1_user_permissions.sql','12_sprint_1_org_permissions.sql','13_sprint_1_role_permissions.sql','14_sprint_1_rbac_acceptance.sql','15_sprint_1_menu_center.sql','16_sprint_1_log_center.sql','V1.1.0__investment_data_risk_bi.sql')
$servers=[Collections.Generic.List[object]]::new();$checks=[ordered]@{};$failures=[Collections.Generic.List[string]]::new()

function Write-Utf8([string]$Path,[string]$Text){[IO.File]::WriteAllText($Path,$Text,(New-Object Text.UTF8Encoding($false)))}
function Check([string]$Name,[bool]$Pass,[string]$Proof=''){$script:checks[$Name]=$Pass;if(-not$Pass){$script:failures.Add("$Name :: $Proof")}}
function Native([string]$Exe,[string[]]$Arguments,[string]$Cwd=''){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{if($Cwd){Push-Location $Cwd};$o=@(& $Exe @Arguments 2>&1);$c=$LASTEXITCODE}finally{if($Cwd){Pop-Location};$ErrorActionPreference=$old};[pscustomobject]@{ExitCode=$c;Output=($o-join"`n")}}
function Sql($Server,[string]$Text,[switch]$NoHeaders,[switch]$NoDatabase){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($Server.Port)",'--user=root','--default-character-set=utf8mb4','--batch','--raw');if($NoHeaders){$a+='--skip-column-names'};if(-not$NoDatabase){$a+='--database=enterprise_platform'};$a+="--execute=$Text";Native $mysql $a}
function SqlFile($Server,[string]$Path,[switch]$NoDatabase){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($Server.Port)",'--user=root','--default-character-set=utf8mb4');if(-not$NoDatabase){$a+='--database=enterprise_platform'};$a+="--execute=source $($Path.Replace('\','/'))";Native $mysql $a}
function Flyway($Server,[string]$Command,[string]$Log,[string]$Location=$fullCopy){$a=@("-url=jdbc:mysql://127.0.0.1:$($Server.Port)/enterprise_platform",'-user=root','-password=',"-locations=filesystem:$($Location.Replace('\','/'))",'-table=flyway_schema_history','-baselineVersion=2.0.0','-baselineDescription=RC2 authoritative baseline','-baselineOnMigrate=false','-validateMigrationNaming=true','-validateOnMigrate=true','-cleanDisabled=true','-outOfOrder=false','-mixed=false','-connectRetries=10',$Command);$r=Native $FlywayPath $a;Write-Utf8 (Join-Path $evidence $Log) ($r.Output+"`n");$r}
function Start-Db([string]$Name,[int]$Port){$root=Join-Path $output $Name;$data=Join-Path $root 'data';New-Item -ItemType Directory -Path $data -Force|Out-Null;$ini=Join-Path $root 'my.ini';Write-Utf8 $ini "[mysqld]`nbasedir=$($MySqlHome.Replace('\','/'))`ndatadir=$($data.Replace('\','/'))`nport=$Port`nbind-address=127.0.0.1`nmysqlx=0`nskip-log-bin`ncharacter-set-server=utf8mb4`ncollation-server=utf8mb4_general_ci`nlog-error=$((Join-Path $root 'mysql.err').Replace('\','/'))`npid-file=$((Join-Path $root 'mysql.pid').Replace('\','/'))`nsecure-file-priv=`"`"`n";$i=Native $mysqld @("--defaults-file=$ini",'--initialize-insecure');if($i.ExitCode){throw $i.Output};$p=Start-Process $mysqld -ArgumentList "--defaults-file=$ini" -WindowStyle Hidden -PassThru;$s=[pscustomobject]@{Name=$Name;Port=$Port;Root=$root;Data=$data;Process=$p;Version=''};$servers.Add($s);for($n=0;$n-lt120;$n++){$ping=Native $mysqladmin @('--protocol=TCP','--host=127.0.0.1',"--port=$Port",'--user=root','ping');if(-not$ping.ExitCode){$id=Sql $s "SELECT CONCAT(@@port,'|',@@datadir,'|',VERSION())" -NoHeaders -NoDatabase;$q=$id.Output.Trim()-split'\|',3;$reported=[IO.Path]::GetFullPath(($q[1]-replace'/','\')).TrimEnd('\');if([int]$q[0]-ne$Port-or$reported-cne$data.TrimEnd('\')-or$q[2]-notmatch'^8\.4\.'){throw "identity mismatch $($id.Output)"};$s.Version=$q[2];return $s};Start-Sleep -Milliseconds 250};throw "start timeout $Name"}
function Baseline($Server){foreach($name in $baselineFiles){$r=SqlFile $Server (Join-Path $baselineCopy $name) -NoDatabase:($name-eq'01_database.sql');if($r.ExitCode){throw "baseline $name :: $($r.Output)"}};$r=Flyway $Server baseline "$($Server.Name)-baseline.log";if($r.ExitCode){throw $r.Output}}
function Get-MigrationHistory($Server){$r=Sql $Server "SELECT version,SUM(success=0),SUM(version='2.6.24' AND success=1),checksum FROM flyway_schema_history WHERE installed_rank=(SELECT MAX(installed_rank) FROM flyway_schema_history) OR version='2.6.24' GROUP BY installed_rank,version,checksum ORDER BY installed_rank DESC LIMIT 1" -NoHeaders;if($r.ExitCode){throw $r.Output};$p=$r.Output.Trim()-split"`t";[pscustomobject]@{Latest=$p[0];Failed=[int]$p[1];Candidate=[int]$p[2];Checksum=$p[3]}}
function Fingerprint($Server){$queries=@("SELECT CONCAT(table_name,'|',engine,'|',table_collation,'|',IFNULL(table_comment,'')) FROM information_schema.tables WHERE table_schema='enterprise_platform' AND table_type='BASE TABLE' ORDER BY table_name","SELECT CONCAT(table_name,'|',ordinal_position,'|',column_name,'|',column_type,'|',is_nullable,'|',IFNULL(column_default,'<NULL>'),'|',IFNULL(collation_name,'<NULL>'),'|',extra,'|',IFNULL(column_comment,'')) FROM information_schema.columns WHERE table_schema='enterprise_platform' ORDER BY table_name,ordinal_position","SELECT CONCAT(table_name,'|',index_name,'|',non_unique,'|',seq_in_index,'|',IFNULL(column_name,'<NULL>'),'|',IFNULL(expression,'<NULL>')) FROM information_schema.statistics WHERE table_schema='enterprise_platform' ORDER BY table_name,index_name,seq_in_index","SELECT CONCAT(trigger_name,'|',event_manipulation,'|',event_object_table,'|',action_timing,'|',action_statement) FROM information_schema.triggers WHERE trigger_schema='enterprise_platform' ORDER BY trigger_name","SELECT CONCAT(constraint_name,'|',table_name,'|',referenced_table_name,'|',unique_constraint_name,'|',update_rule,'|',delete_rule) FROM information_schema.referential_constraints WHERE constraint_schema='enterprise_platform' ORDER BY table_name,constraint_name","SELECT CONCAT(tc.table_name,'|',tc.constraint_name,'|',cc.check_clause) FROM information_schema.table_constraints tc JOIN information_schema.check_constraints cc ON cc.constraint_schema=tc.constraint_schema AND cc.constraint_name=tc.constraint_name WHERE tc.constraint_schema='enterprise_platform' AND tc.constraint_type='CHECK' ORDER BY tc.table_name,tc.constraint_name");$b=[Text.StringBuilder]::new();foreach($q in $queries){$r=Sql $Server $q -NoHeaders;if($r.ExitCode){throw $r.Output};[void]$b.AppendLine($r.Output)};$path=Join-Path $evidence "$($Server.Name)-schema.txt";Write-Utf8 $path $b.ToString();(Get-FileHash $path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Row([long]$Id,[string]$Previous,[long]$Enterprise,[long]$Org,[long]$Def,[long]$Ver,[long]$Node,[string]$Role,[string]$State,[int]$Revision){$prev=if($Previous){$Previous}else{'NULL'};$approval=if($State-eq'PROPOSED'){'NULL,NULL'}else{"'test-approver','2026-08-26 02:01:00.000'"};$enable=if($State-in@('ENABLED','SUSPENDED')){"'test-enabler','2026-08-26 02:02:00.000'"}else{'NULL,NULL'};$suspend=if($State-eq'SUSPENDED'){"'2026-08-26 02:03:00.000'"}else{'NULL'};$revoke=if($State-eq'REVOKED'){"'2026-08-26 02:04:00.000'"}else{'NULL'};"INSERT INTO workflow_role_canary_scope_governance(id,previous_record_id,enterprise_id,organization_id,definition_id,definition_version_id,node_id,role_code,governance_state,governance_revision,directory_revision,directory_candidate_count,directory_result_hash,version_binding_hash,manifest_hash,content_hash,release_tag,release_commit,structural_fingerprint,approval_actor,approved_at,enablement_actor,enabled_at,suspended_at,revoked_at,reason,effective_from,created_by,updated_by) VALUES($Id,$prev,$Enterprise,$Org,$Def,$Ver,$Node,'$Role','$State',$Revision,'1',2,REPEAT('a',64),REPEAT('b',64),REPEAT('c',64),REPEAT('d',64),'workflow-v1.0.0-rc2','740bee63e79a2744eb06ff693b17e7ed3fdf9375',REPEAT('e',64),$approval,$enable,$suspend,$revoke,'RC2-S11.2','2026-08-26 02:00:00.000','RC2-S11.2','RC2-S11.2')"}
function Expect-Ok($Server,[string]$Name,[string]$Text){$r=Sql $Server $Text;Check $Name (-not$r.ExitCode) $r.Output;$r}
function Expect-Fail($Server,[string]$Name,[string]$Text,[string]$Pattern=''){ $r=Sql $Server $Text;$ok=$r.ExitCode-ne0-and(-not$Pattern-or$r.Output-match$Pattern);Check $Name $ok $r.Output;$r}
function Seed-Gate($Server){Expect-Ok $Server 'GATE_ROOT' (Row 9001 '' 991001 991101 991401 991402 991404 'RC2_CANARY_GATE_TEST' 'PROPOSED' 1)|Out-Null;Expect-Ok $Server 'GATE_APPROVE' (Row 9002 '9001' 991001 991101 991401 991402 991404 'RC2_CANARY_GATE_TEST' 'APPROVED_NOT_ENABLED' 2)|Out-Null;Expect-Ok $Server 'GATE_ENABLE' (Row 9003 '9002' 991001 991101 991401 991402 991404 'RC2_CANARY_GATE_TEST' 'ENABLED' 3)|Out-Null;$scopes=@(@('FEATURE_FLAG','GLOBAL','GLOBAL','ON'),@('FEATURE_FLAG','ENTERPRISE','ENTERPRISE|991001','ON'),@('FEATURE_FLAG','WORKFLOW_DEFINITION','WORKFLOW_DEFINITION|991001|DEF:991401','ON'),@('KILL_SWITCH','GLOBAL','GLOBAL','ALLOW'),@('KILL_SWITCH','ENTERPRISE','ENTERPRISE|991001','ALLOW'),@('KILL_SWITCH','DEFINITION_VERSION','DEFINITION_VERSION|991001|DEF:991401|VER:991402','ALLOW'));$id=9100;foreach($x in $scopes){$id++;$q="INSERT INTO workflow_role_runtime_governance_control(id,control_type,scope_type,scope_key,decision,config_version,effective_from,policy_payload_hash,evidence_hash,changed_by,approved_by,reason,created_by,updated_by) VALUES($id,'$($x[0])','$($x[1])','$($x[2])','$($x[3])',1,'2026-08-26 01:00:00.000',REPEAT('a',64),REPEAT('b',64),'test','test','RC2-S11.2','test','test')";Expect-Ok $Server "GATE_CONTROL_$id" $q|Out-Null}}
function Concurrent($Server,[string]$Name,[string]$One,[string]$Two){$job1=Start-Job -ScriptBlock {param($exe,$port,$sql)&$exe '--protocol=TCP' '--host=127.0.0.1' "--port=$port" '--user=root' '--database=enterprise_platform' "--execute=$sql" 2>&1;$LASTEXITCODE} -ArgumentList $mysql,$Server.Port,$One;$job2=Start-Job -ScriptBlock {param($exe,$port,$sql)&$exe '--protocol=TCP' '--host=127.0.0.1' "--port=$port" '--user=root' '--database=enterprise_platform' "--execute=$sql" 2>&1;$LASTEXITCODE} -ArgumentList $mysql,$Server.Port,$Two;Wait-Job $job1,$job2|Out-Null;$o1=@(Receive-Job $job1);$o2=@(Receive-Job $job2);Remove-Job $job1,$job2;$codes=@($o1[-1],$o2[-1]);Check $Name ((@($codes|Where-Object{$_-eq0}).Count-eq1)-and(@($codes|Where-Object{$_-ne0}).Count-eq1)) (($o1+$o2)-join"`n")}
function Stop-All{foreach($s in $servers){[void](Native $mysqladmin @('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','shutdown'));if(-not$s.Process.HasExited){$s.Process.WaitForExit(10000)|Out-Null}}}
function Remove-Data{foreach($s in $servers){$p=[IO.Path]::GetFullPath($s.Root);if(-not$p.StartsWith($output+'\',[StringComparison]::OrdinalIgnoreCase)){throw "unsafe cleanup $p"};if(Test-Path $p){Remove-Item -LiteralPath $p -Recurse -Force}}}

$freshA=$null;$freshB=$null;$upgrade=$null;$ha=$null;$hb=$null;$hu=$null;$fpa='';$fpb='';$fpu='';$noopA='FAIL';$noopB='FAIL';$noopU='FAIL';$checksum='';$mapping='FAIL';$realGate='FAIL'
try{
    if($output-notmatch'^D:\\codex-rc2-v2624-[A-Za-z0-9._-]+$'-or(Test-Path $output)){throw "unsafe/existing OutputRoot $output"};if(@(@($FreshAPort,$FreshBPort,$UpgradePort)|Sort-Object -Unique).Count-ne3-or@($FreshAPort,$FreshBPort,$UpgradePort)-contains34061){throw'unsafe ports'};foreach($p in @($FreshAPort,$FreshBPort,$UpgradePort)){if(Get-NetTCPConnection -LocalPort $p -State Listen -ErrorAction SilentlyContinue){throw "occupied $p"}};foreach($t in @($mysqld,$mysql,$mysqladmin,$FlywayPath,$MavenPath,(Join-Path $JavaHome 'bin\java.exe'))){if(-not(Test-Path $t -PathType Leaf)){throw "missing $t"}}
    New-Item -ItemType Directory -Path $output,$evidence,$baselineCopy,$fullCopy,$upgradeCopy|Out-Null
    $actual=@(Get-ChildItem $baselineSource -File -Filter '*.sql'|Sort-Object Name|ForEach-Object Name);if(($actual-join"`n")-cne(($baselineFiles|Sort-Object)-join"`n")){throw'17 baseline drift'};foreach($n in $baselineFiles){Copy-Item (Join-Path $baselineSource $n) (Join-Path $baselineCopy $n)}
    $assets=@(Get-ChildItem $migrationSource -File -Filter 'V*.sql'|ForEach-Object{if($_.Name-notmatch'^V(\d+\.\d+\.\d+)__.+\.sql$'){throw"bad name $($_.Name)"};[pscustomobject]@{File=$_;Version=[version]$Matches[1];Text=$Matches[1]}}|Sort-Object Version);if($assets.Count-ne46-or$assets[-1].Text-cne'2.6.24'){throw "migration count/latest $($assets.Count)/$($assets[-1].Text)"};$lines=@(Get-Content $manifest|Where-Object{$_-match'^[0-9a-f]{64}  \S+$'});if($lines.Count-ne46){throw'SHA count'};$map=@{};foreach($l in $lines){$x=$l-split'  ',2;$map[$x[1]]=$x[0]};foreach($a in $assets){$hash=(Get-FileHash $a.File.FullName -Algorithm SHA256).Hash.ToLowerInvariant();if($map[$a.File.Name]-cne$hash){throw"SHA drift $($a.File.Name)"};Copy-Item $a.File.FullName (Join-Path $fullCopy $a.File.Name);if($a.Version-le[version]'2.6.23'){Copy-Item $a.File.FullName (Join-Path $upgradeCopy $a.File.Name)}};if($map['V2.6.24__create_exact_canary_scope_governance.sql']-cne$expectedSha){throw'V2.6.24 SHA drift'};Check 'MIGRATION_SHA_46_OF_46' $true
    $fv=Native $FlywayPath @('-v');if($fv.ExitCode -or $fv.Output -notmatch '13\.0\.0'){throw $fv.Output}
    $freshA=Start-Db fresh-a $FreshAPort;$freshB=Start-Db fresh-b $FreshBPort;$upgrade=Start-Db upgrade $UpgradePort;foreach($s in @($freshA,$freshB,$upgrade)){Baseline $s}
    foreach($s in @($freshA,$freshB)){if((Flyway $s migrate "$($s.Name)-migrate.log").ExitCode){throw'fresh migrate'};Check "$($s.Name)_VALIDATE" (-not(Flyway $s validate "$($s.Name)-validate.log").ExitCode);$n=Flyway $s migrate "$($s.Name)-noop.log";$value=if(-not$n.ExitCode-and$n.Output-match'(?i)No migration necessary|up to date'){'NO_OP'}else{'FAIL'};if($s.Name-eq'fresh-a'){$noopA=$value;$ha=Get-MigrationHistory $s;$fpa=Fingerprint $s}else{$noopB=$value;$hb=Get-MigrationHistory $s;$fpb=Fingerprint $s};Check "$($s.Name)_NOOP" ($value-eq'NO_OP') $n.Output}
    if((Flyway $upgrade migrate 'upgrade-to-v2623.log' $upgradeCopy).ExitCode){throw'upgrade source migrate'};$source=Get-MigrationHistory $upgrade;Check 'UPGRADE_SOURCE_2623' ($source.Latest-ceq'2.6.23') $source.Latest;if((Flyway $upgrade migrate 'upgrade-v2624.log').ExitCode){throw'upgrade V2624'};Check 'UPGRADE_VALIDATE' (-not(Flyway $upgrade validate 'upgrade-validate.log').ExitCode);$n=Flyway $upgrade migrate 'upgrade-noop.log';$noopU=if(-not$n.ExitCode-and$n.Output-match'(?i)No migration necessary|up to date'){'NO_OP'}else{'FAIL'};Check 'UPGRADE_NOOP' ($noopU-eq'NO_OP') $n.Output;$hu=Get-MigrationHistory $upgrade;$fpu=Fingerprint $upgrade
    Check 'FRESH_HISTORY' ($ha.Latest-ceq'2.6.24'-and$ha.Failed-eq0-and$ha.Candidate-eq1) ($ha|ConvertTo-Json -Compress);Check 'DOUBLE_FRESH' ($fpa-ceq$fpb) "$fpa/$fpb";Check 'FRESH_UPGRADE' ($fpa-ceq$fpu) "$fpa/$fpu";$checksum=$ha.Checksum
    $schema=Sql $freshA "SELECT column_name,is_nullable FROM information_schema.columns WHERE table_schema='enterprise_platform' AND table_name='workflow_role_canary_scope_governance' AND column_name IN ('enterprise_id','organization_id','definition_id','definition_version_id','node_id','role_code') ORDER BY ordinal_position" -NoHeaders;Check 'SIX_DIMENSION_SCHEMA' ((@($schema.Output.Trim()-split"`n").Count-eq6)-and$schema.Output-notmatch"`tYES") $schema.Output
    Expect-Ok $freshA 'ROOT' (Row 1001 '' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'PROPOSED' 1)|Out-Null;Expect-Fail $freshA 'DUPLICATE_ROOT' (Row 1002 '' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'PROPOSED' 1)|Out-Null;Expect-Ok $freshA 'APPROVE' (Row 1003 '1001' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'APPROVED_NOT_ENABLED' 2)|Out-Null;$approved=Sql $freshA "SELECT governance_state,(enabled_at IS NULL) FROM workflow_role_canary_scope_governance WHERE id=1003" -NoHeaders;Check 'APPROVE_NOT_ENABLE' ($approved.Output.Trim()-eq"APPROVED_NOT_ENABLED`t1") $approved.Output;Expect-Ok $freshA 'ENABLE' (Row 1004 '1003' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'ENABLED' 3)|Out-Null;Expect-Ok $freshA 'SUSPEND' (Row 1005 '1004' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'SUSPENDED' 4)|Out-Null;Expect-Ok $freshA 'RESUME' (Row 1006 '1005' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'ENABLED' 5)|Out-Null;Expect-Ok $freshA 'REVOKE' (Row 1007 '1006' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'REVOKED' 6)|Out-Null;Expect-Fail $freshA 'REVOKED_ENABLE' (Row 1008 '1007' 990001 990101 990401 990402 990404 'RC1_TEST_CANARY_APPROVER' 'ENABLED' 7) 'CANARY_SCOPE_TRANSITION_INVALID'|Out-Null;Expect-Fail $freshA 'UPDATE_REJECT' "UPDATE workflow_role_canary_scope_governance SET reason='x' WHERE id=1001" 'CANARY_SCOPE_APPEND_ONLY'|Out-Null;Expect-Fail $freshA 'DELETE_REJECT' "DELETE FROM workflow_role_canary_scope_governance WHERE id=1001" 'CANARY_SCOPE_APPEND_ONLY'|Out-Null
    Expect-Ok $freshA 'ILLEGAL_ROOT' (Row 2001 '' 990002 990102 990402 990403 990405 'RC2_TEST_ROLE' 'PROPOSED' 1)|Out-Null;Expect-Fail $freshA 'PROPOSED_ENABLE' (Row 2002 '2001' 990002 990102 990402 990403 990405 'RC2_TEST_ROLE' 'ENABLED' 2) 'CANARY_SCOPE_TRANSITION_INVALID'|Out-Null;Expect-Ok $freshA 'DIRECT_REVOKE' (Row 2003 '2001' 990002 990102 990402 990403 990405 'RC2_TEST_ROLE' 'REVOKED' 2)|Out-Null
    Expect-Fail $freshA 'NULL_ORG' ((Row 3001 '' 990003 990103 990403 990404 990406 'RC2_NULL' 'PROPOSED' 1)-replace',990103,',',NULL,')|Out-Null;Expect-Fail $freshA 'NULL_ROLE' ((Row 3002 '' 990004 990104 990404 990405 990407 'RC2_NULL' 'PROPOSED' 1)-replace"'RC2_NULL'","NULL")|Out-Null;Expect-Ok $freshA 'WILDCARD_DB_ISOLATED' (Row 3003 '' 990005 990105 990405 990406 990408 '*' 'PROPOSED' 1)|Out-Null;$wild=Sql $freshA "SELECT COUNT(*) FROM workflow_role_canary_scope_governance WHERE enterprise_id=990005 AND role_code='RC2_REAL_ROLE'" -NoHeaders;Check 'WILDCARD_GATE_DENY' ($wild.Output.Trim()-eq'0') $wild.Output
    $legacy="INSERT INTO workflow_role_runtime_governance_control(id,control_type,scope_type,scope_key,enterprise_id,definition_id,definition_version_id,node_id,decision,config_version,effective_from,policy_payload_hash,evidence_hash,changed_by,approved_by,reason,created_by,updated_by) VALUES(8001,'CANARY','NODE','CANARY|990006|DEF:990406|VER:990407|NODE:990409','990006',990406,990407,990409,'ALLOW',1,'2026-08-26 01:00:00.000',REPEAT('a',64),REPEAT('b',64),'test','test','legacy','test','test')";Expect-Ok $freshA 'LEGACY_CONTROL' $legacy|Out-Null;$legacyCount=Sql $freshA "SELECT COUNT(*) FROM workflow_role_canary_scope_governance WHERE enterprise_id=990006" -NoHeaders;Check 'LEGACY_FAIL_CLOSED' ($legacyCount.Output.Trim()-eq'0') $legacyCount.Output
    Seed-Gate $freshA
    for($case=0;$case-lt4;$case++){ $base=10000+$case*100;$enterprise=992000+$case;Expect-Ok $freshA "CONC_ROOT_$case" (Row $base '' $enterprise 992101 992401 992402 992404 "RC2_CONC_$case" 'PROPOSED' 1)|Out-Null;if($case-ge2){Expect-Ok $freshA "CONC_APPROVE_$case" (Row ($base+1) "$base" $enterprise 992101 992401 992402 992404 "RC2_CONC_$case" 'APPROVED_NOT_ENABLED' 2)|Out-Null;$parent=$base+1;$rev=3;$oneState='ENABLED';$twoState='REVOKED'}else{$parent=$base;$rev=2;$oneState='APPROVED_NOT_ENABLED';$twoState=if($case-eq0){'APPROVED_NOT_ENABLED'}else{'REVOKED'}};Concurrent $freshA "CONCURRENCY_$case" (Row ($base+10) "$parent" $enterprise 992101 992401 992402 992404 "RC2_CONC_$case" $oneState $rev) (Row ($base+11) "$parent" $enterprise 992101 992401 992402 992404 "RC2_CONC_$case" $twoState $rev)}
    $oldJava=$env:JAVA_HOME;$oldUrl=$env:DB_URL;$oldUser=$env:DB_USERNAME;$oldPass=$env:DB_PASSWORD;$oldV=$env:V2624_MYSQL_URL;$oldMap=$env:RC2_MAPPING_DB_URL;$oldJwt=$env:JWT_SECRET;$env:JAVA_HOME=$JavaHome;$env:DB_URL="jdbc:mysql://127.0.0.1:$FreshAPort/enterprise_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false";$env:DB_USERNAME='root';$env:DB_PASSWORD='';$env:V2624_MYSQL_URL=$env:DB_URL;$env:RC2_MAPPING_DB_URL=$env:DB_URL;$env:JWT_SECRET='rc2-s11-2-ephemeral-jwt-secret-0000000000000000';try{$mr=Native $MavenPath @('-Dtest=DatabaseMappingCheckerRealMysqlTest,V2624CanaryGovernanceRealMysqlTest','test') (Join-Path $workspace 'backend');Write-Utf8 (Join-Path $evidence 'real-application-tests.log') ($mr.Output+"`n");$mapping=if(-not$mr.ExitCode-and$mr.Output-match'DatabaseMappingCheckerRealMysqlTest' -and$mr.Output-notmatch'CanaryGovernanceEntity.*result=(INCONSISTENT|TABLE_NOT_FOUND)'){'PASS'}else{'FAIL'};$realGate=if(-not$mr.ExitCode-and$mr.Output-match'V2624CanaryGovernanceRealMysqlTest' -and$mr.Output-match'Tests run: 2, Failures: 0, Errors: 0, Skipped: 0'){'PASS'}else{'FAIL'};Check 'MAPPING' ($mapping-eq'PASS') $mr.Output;Check 'REAL_GATE' ($realGate-eq'PASS') $mr.Output}finally{$env:JAVA_HOME=$oldJava;$env:DB_URL=$oldUrl;$env:DB_USERNAME=$oldUser;$env:DB_PASSWORD=$oldPass;$env:V2624_MYSQL_URL=$oldV;$env:RC2_MAPPING_DB_URL=$oldMap;$env:JWT_SECRET=$oldJwt}
}catch{$failures.Add($_.Exception.Message)}finally{Stop-All;Remove-Data;$result=if($failures.Count-eq0-and@($checks.Values|Where-Object{-not$_}).Count-eq0){'PASS'}else{'FAIL'};$summary=[ordered]@{result=$result;output_root=$output;evidence_root=$evidence;mysql_versions=@($freshA.Version,$freshB.Version,$upgrade.Version);v2624_sha256=$expectedSha;v2624_flyway_checksum=$checksum;fresh_a_fingerprint=$fpa;fresh_b_fingerprint=$fpb;upgrade_fingerprint=$fpu;fresh_a_noop=$noopA;fresh_b_noop=$noopB;upgrade_noop=$noopU;checks=$checks;failures=@($failures);rc1_test_database_touched=$false;persistent_rc2_database_touched=$false;role_runtime='DISABLED';canary='NOT_AUTHORIZED_NOT_ENABLED';kill_switch='STOP_NEW_AND_CLAIM'};Write-Utf8 (Join-Path $evidence 'summary.json') (($summary|ConvertTo-Json -Depth 8)+"`n");$checks.GetEnumerator()|ForEach-Object{"$($_.Key)=$(if($_.Value){'PASS'}else{'FAIL'})"};"V2624_SHA256=$expectedSha";"V2624_FLYWAY_CHECKSUM=$checksum";"FRESH_A_MYSQL_VERSION=$($freshA.Version)";"FRESH_LATEST_MIGRATION=$($ha.Latest)";"FRESH_FAILED_MIGRATIONS=$($ha.Failed)";"FRESH_SECOND_MIGRATE=$noopA";"FRESH_SCHEMA_FINGERPRINT=$fpa";"UPGRADE_MYSQL_VERSION=$($upgrade.Version)";"UPGRADE_SOURCE_VERSION=2.6.23";"UPGRADE_TARGET_VERSION=$($hu.Latest)";"UPGRADE_FAILED_MIGRATIONS=$($hu.Failed)";"UPGRADE_SECOND_MIGRATE=$noopU";"UPGRADE_SCHEMA_FINGERPRINT=$fpu";"EVIDENCE_ROOT=$evidence";"RC2_S11_2=$result";if($result-ne'PASS'){$failures|ForEach-Object{Write-Error $_};exit 2}}
