param(
  [string]$OutputRoot="D:\codex-validation-org-dir-1-$((Get-Date).ToString('yyyyMMdd-HHmmss'))",
  [int]$BasePort=36710
)
$ErrorActionPreference='Stop'
$workspace=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$mysqlHome='C:\Program Files\MySQL\MySQL Server 8.4';$mysqld=Join-Path $mysqlHome 'bin\mysqld.exe';$mysql=Join-Path $mysqlHome 'bin\mysql.exe';$mysqladmin=Join-Path $mysqlHome 'bin\mysqladmin.exe'
$flyway='C:\Users\WUKONG\AppData\Local\Temp\enterprise-v246-acceptance-68bf692b16d34ee191946695ae0bef9b\flyway-fresh\flyway-13.0.0\flyway.cmd'
$migrationRoot=Join-Path $workspace 'database\migration\mysql';$baselineRoot=Join-Path $workspace 'database\mysql';$fingerprintSql=Join-Path $baselineRoot 'verification\schema_fingerprint.sql'
$baselineFiles=@('01_database.sql','02_sys.sql','03_hr.sql','04_party.sql','05_project.sql','06_operation.sql','07_investment.sql','08_data_asset.sql','09_risk.sql','10_init_data.sql','11_sprint_1_user_permissions.sql','12_sprint_1_org_permissions.sql','13_sprint_1_role_permissions.sql','14_sprint_1_rbac_acceptance.sql','15_sprint_1_menu_center.sql','16_sprint_1_log_center.sql','V1.1.0__investment_data_risk_bi.sql')
foreach($a in @($mysqld,$mysql,$mysqladmin,$flyway,$fingerprintSql)){if(!(Test-Path -LiteralPath $a)){throw "Missing validation asset: $a"}}
if(Test-Path -LiteralPath $OutputRoot){throw "Disposable root exists: $OutputRoot"};if(!$OutputRoot.StartsWith('D:\codex-validation-org-dir-1-')){throw 'Unsafe validation root'}
$evidence=Join-Path $OutputRoot 'evidence';$full=Join-Path $OutputRoot 'migrations-full';$to2616=Join-Path $OutputRoot 'migrations-to-2616';$baseline=Join-Path $OutputRoot 'baseline';New-Item -ItemType Directory -Path $evidence,$full,$to2616,$baseline -Force|Out-Null
Get-ChildItem $migrationRoot -Filter 'V*.sql' -File|Copy-Item -Destination $full
Get-ChildItem $migrationRoot -Filter 'V*.sql' -File|Where-Object Name -ne 'V2.6.17__create_approval_role_directory.sql'|Copy-Item -Destination $to2616
foreach($n in $baselineFiles){Copy-Item (Join-Path $baselineRoot $n) (Join-Path $baseline $n)}
$servers=@();$checks=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[string]]::new()
function Add([string]$name,[bool]$pass,[string]$proof=''){$checks.Add([ordered]@{name=$name;pass=$pass;proof=$proof});if(!$pass){$failures.Add("$name :: $proof")}}
function New-Server([string]$name,[int]$port){if(Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue|Where-Object State -ne TimeWait){throw "Port in use $port"};$root=Join-Path $OutputRoot $name;$data=Join-Path $root data;$logs=Join-Path $root logs;New-Item -ItemType Directory $data,$logs -Force|Out-Null;$ini=Join-Path $root my.ini;[IO.File]::WriteAllText($ini,@"
[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=$($data.Replace('\','/'))
port=$port
bind-address=127.0.0.1
mysqlx=0
skip-log-bin
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
log-error=$((Join-Path $logs 'mysql.err').Replace('\','/'))
pid-file=$((Join-Path $root 'mysql.pid').Replace('\','/'))
secure-file-priv=""
"@,[Text.UTF8Encoding]::new($false));&$mysqld "--defaults-file=$ini" --initialize-insecure;if($LASTEXITCODE){throw "init failed $name"};$p=Start-Process $mysqld -ArgumentList "--defaults-file=$ini" -WindowStyle Hidden -PassThru;$script:servers+=$p;foreach($i in 1..100){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 --port=$port --user=root ping 2>$null|Out-Null;$c=$LASTEXITCODE;$ErrorActionPreference=$old;if(!$c){return @{Name=$name;Port=$port;Root=$root}};Start-Sleep -Milliseconds 300};throw "not ready $name"}
function DB($s,[string]$sql,[switch]$raw){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--database=enterprise_platform');if($raw){$a+=@('--batch','--raw','--skip-column-names')};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=&$mysql @a "--execute=$sql" 2>&1;$c=$LASTEXITCODE;$ErrorActionPreference=$old;@{ExitCode=$c;Output=($o-join"`n")}}
function Baseline($s){foreach($n in $baselineFiles){$f=Join-Path $baseline $n;$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--default-character-set=utf8mb4');if($n-ne'01_database.sql'){$a+='--database=enterprise_platform'};$o=&$mysql @a "--execute=source $($f.Replace('\','/'))" 2>&1;if($LASTEXITCODE){throw "baseline $n failed $($o-join' ')"}}}
function Fly($s,[string]$loc,[string]$command,[string]$target=''){$a=@("-url=jdbc:mysql://127.0.0.1:$($s.Port)/enterprise_platform",'-user=root','-password=',"-locations=filesystem:$($loc.Replace('\','/'))",'-baselineOnMigrate=true','-baselineVersion=2.0.0','-validateMigrationNaming=true','-cleanDisabled=true','-connectRetries=10');if($target){$a+="-target=$target"};$a+=$command;$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=&$flyway @a 2>&1;$c=$LASTEXITCODE;$ErrorActionPreference=$old;$o|Set-Content (Join-Path $evidence "$($s.Name)-$command-$([DateTime]::UtcNow.Ticks).log");@{ExitCode=$c;Output=($o-join"`n")}}
function MustFly($s,$loc,$cmd,$target=''){$r=Fly $s $loc $cmd $target;if($r.ExitCode){throw $r.Output};$r}
function Reject($s,$name,$sql,$expected=''){$r=DB $s $sql;$pass=$r.ExitCode-ne0-and(!$expected-or$r.Output.Contains($expected));Add $name $pass $r.Output}
function Fingerprint($s){$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--database=enterprise_platform','--batch','--raw','--skip-column-names');$rows=Get-Content $fingerprintSql -Raw|&$mysql @a;$tr=&$mysql @a '--execute=SELECT CONCAT("TRIGGER|",trigger_name,"|",event_manipulation,"|",event_object_table,"|",action_timing,"|",REPLACE(REPLACE(action_statement,CHAR(13)," "),CHAR(10)," ")) FROM information_schema.triggers WHERE trigger_schema=DATABASE() ORDER BY trigger_name';$all=@($rows)+@($tr);$org=$all|Where-Object{$_-match 'approval_role|sys_org|sys_user'};$dir=$all|Where-Object{$_-match 'approval_role'};$o=@{};foreach($p in @(@('full',$all),@('organization',$org),@('directory',$dir))){$f=Join-Path $evidence "$($s.Name)-$($p[0]).txt";[IO.File]::WriteAllText($f,(($p[1]-join"`n")+"`n"),[Text.UTF8Encoding]::new($false));$o[$p[0]]=(Get-FileHash $f -Algorithm SHA256).Hash.ToLower()};$o}
function Concurrent($s,[string]$name,[string]$sql1,[string]$sql2){$i1=Join-Path $evidence "$name-1.sql";$i2=Join-Path $evidence "$name-2.sql";$o1=Join-Path $evidence "$name-1.out";$o2=Join-Path $evidence "$name-2.out";$e1=Join-Path $evidence "$name-1.err";$e2=Join-Path $evidence "$name-2.err";[IO.File]::WriteAllText($i1,$sql1,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($i2,$sql2,[Text.UTF8Encoding]::new($false));$a=@('--protocol=TCP','--host=127.0.0.1',"--port=$($s.Port)",'--user=root','--database=enterprise_platform','--force');$p1=Start-Process $mysql -ArgumentList $a -WindowStyle Hidden -PassThru -RedirectStandardInput $i1 -RedirectStandardOutput $o1 -RedirectStandardError $e1;$p2=Start-Process $mysql -ArgumentList $a -WindowStyle Hidden -PassThru -RedirectStandardInput $i2 -RedirectStandardOutput $o2 -RedirectStandardError $e2;$p1.WaitForExit();$p2.WaitForExit();$t1=(Get-Content $e1 -ErrorAction SilentlyContinue)-join' ';$t2=(Get-Content $e2 -ErrorAction SilentlyContinue)-join' ';@{errors=@($t1,$t2).Where({$_-match'ERROR'}).Count;deadlock=("$t1 $t2"-match'ERROR 1213|ERROR 1205');text="$t1 | $t2"}}
function Seed($s){$sql=@"
INSERT INTO sys_org(id,org_code,org_name,org_type,parent_id,tree_path,tree_level,status,create_by,update_by,deleted,delete_token,version) VALUES(880001,'ORG_A','Org A','DEPARTMENT',NULL,'/',1,1,'test','test',0,0,0),(880002,'ORG_B','Org B','DEPARTMENT',NULL,'/',1,1,'test','test',0,0,0);
INSERT INTO sys_user(id,username,password,real_name,org_id,status,create_by,update_by,deleted,delete_token,version) VALUES(881001,'orgdir-u1','hash','Fixture U1',880001,1,'test','test',0,0,0),(881002,'orgdir-u2','hash','Fixture U2',880001,1,'test','test',0,0,0),(881003,'orgdir-u3','hash','Fixture U3',880002,1,'test','test',0,0,0);
INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by,deleted,delete_token,version) VALUES(882001,'E1','TEST_APPROVER','Test Approver','PROCESS_APPROVAL_ROLE','BUSINESS_ORG','ACTIVE','test','test',0,0,0);
INSERT INTO approval_role_revision_head(id,enterprise_id,organization_id,role_code,current_revision,current_result_hash,create_by,update_by,deleted,delete_token,version) VALUES(883001,'E1',880001,'TEST_APPROVER',1,REPEAT('a',64),'test','test',0,0,0);
INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by,deleted,delete_token,version) VALUES(884001,'E1',880001,'TEST_APPROVER',1,REPEAT('a',64),'BATCH','initial empty authority','2026-01-01 00:00:00.000','2026-01-01 00:00:00.000','test',NULL,NULL,'test','test',0,0,0);
"@;$r=DB $s $sql;if($r.ExitCode){throw $r.Output}}
function AssignmentSql($id,$user,$from,$to,$ref,$hashChar){$toSql=if($to){"'$to'"}else{'NULL'};"INSERT INTO approval_role_assignment(id,enterprise_id,organization_id,role_id,role_code,user_id,effective_from,effective_to,status,source_type,source_system,source_reference,source_reference_hash,evidence_priority,recorded_at,assignment_key_hash,create_by,update_by,deleted,delete_token,version) VALUES($id,'E1',880001,882001,'TEST_APPROVER',$user,'$from',$toSql,'ACTIVE','GOVERNANCE_DECISION','GOV','$ref',REPEAT('$hashChar',64),1,'2026-01-01 00:00:00.000',SHA2(CONCAT('$id','$ref'),256),'test','test',0,0,0)"}
try{
 $fresh=New-Server fresh ($BasePort+1);$upgrade=New-Server upgrade ($BasePort+2);Baseline $fresh;Baseline $upgrade
 $fm=MustFly $fresh $full migrate;MustFly $fresh $full validate|Out-Null;$fn=MustFly $fresh $full migrate;Add FRESH $true;Add FRESH_NOOP ($fn.Output-match'No migration necessary')
 MustFly $upgrade $to2616 migrate '2.6.16'|Out-Null;$before=[int](DB $upgrade 'SELECT COUNT(*) FROM flyway_schema_history WHERE success=1' -raw).Output.Trim();$um=MustFly $upgrade $full migrate;MustFly $upgrade $full validate|Out-Null;$un=MustFly $upgrade $full migrate;$after=[int](DB $upgrade 'SELECT COUNT(*) FROM flyway_schema_history WHERE success=1' -raw).Output.Trim();Add UPGRADE_ONLY_V2617 ($after-$before-eq1) "$before->$after";Add UPGRADE_NOOP ($un.Output-match'No migration necessary')
 $ff=Fingerprint $fresh;$uf=Fingerprint $upgrade;foreach($k in @('full','organization','directory')){Add "FINGERPRINT_$($k.ToUpper())" ($ff[$k]-eq$uf[$k]) "$($ff[$k]) / $($uf[$k])"}
 $checksum=(DB $fresh "SELECT checksum FROM flyway_schema_history WHERE version='2.6.17' AND success=1" -raw).Output.Trim();$history=(DB $fresh "SELECT installed_rank,version,description,checksum,success FROM flyway_schema_history ORDER BY installed_rank" -raw).Output;$history|Set-Content (Join-Path $evidence history.txt)
 Seed $fresh
 Reject $fresh role_code_lower "INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by) VALUES(900001,'E1','test_bad','x','PROCESS_APPROVAL_ROLE','BUSINESS_ORG','ACTIVE','t','t')"
 Reject $fresh role_type "INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by) VALUES(900002,'E1','TEST_BAD','x','SYSTEM_ROLE','BUSINESS_ORG','ACTIVE','t','t')"
 Reject $fresh role_scope "INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by) VALUES(900003,'E1','TEST_BAD','x','PROCESS_APPROVAL_ROLE','GROUP','ACTIVE','t','t')"
 Reject $fresh duplicate_role "INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by) VALUES(900004,'E1','TEST_APPROVER','x','PROCESS_APPROVAL_ROLE','BUSINESS_ORG','ACTIVE','t','t')"
 Reject $fresh invalid_org_fk "INSERT INTO approval_role_revision_head(id,enterprise_id,organization_id,role_code,current_revision,create_by,update_by) VALUES(900005,'E1',999999,'TEST_APPROVER',0,'t','t')"
 $r=DB $fresh "INSERT INTO approval_role(id,enterprise_id,role_code,role_name,role_type,organization_scope_type,status,create_by,update_by,deleted,delete_token,version) VALUES(882002,'E2','TEST_APPROVER','Other Enterprise Approver','PROCESS_APPROVAL_ROLE','BUSINESS_ORG','ACTIVE','test','test',0,0,0)";if($r.ExitCode){throw $r.Output}
 Reject $fresh role_enterprise_mismatch ((AssignmentSql 900006 881001 '2026-01-01 00:00:00.000' '' WRONG-ENTERPRISE 6).Replace(',882001,',',882002,')) 'APPROVAL_ROLE_ASSIGNMENT_ROLE_MISMATCH'
 Reject $fresh interval_invalid (AssignmentSql 900010 881001 '2026-06-01 00:00:00.000' '2026-06-01 00:00:00.000' X 1)
 Reject $fresh hash_upper "INSERT INTO approval_role_assignment(id,enterprise_id,organization_id,role_id,role_code,user_id,effective_from,status,source_type,source_system,source_reference,source_reference_hash,evidence_priority,recorded_at,assignment_key_hash,create_by,update_by) VALUES(900011,'E1',880001,882001,'TEST_APPROVER',881001,'2026-01-01','ACTIVE','IMPORT','IMP','X',REPEAT('A',64),1,'2026-01-01',REPEAT('b',64),'t','t')"
 $a1=AssignmentSql 885001 881001 '2026-01-01 00:00:00.000' '2026-06-01 00:00:00.000' DEC-A 1;$a2=AssignmentSql 885002 881002 '2026-06-01 00:00:00.000' '' DEC-B 2;$a3=AssignmentSql 885003 881001 '2026-01-01 00:00:00.000' '2026-06-01 00:00:00.000' HR-A 3;foreach($sql in @($a1,$a2,$a3)){$r=DB $fresh $sql;if($r.ExitCode){throw $r.Output}}
 $may=(DB $fresh "SELECT GROUP_CONCAT(DISTINCT user_id ORDER BY user_id),COUNT(*) FROM approval_role_assignment WHERE enterprise_id='E1' AND organization_id=880001 AND role_code='TEST_APPROVER' AND status='ACTIVE' AND effective_from<='2026-05-01' AND (effective_to IS NULL OR '2026-05-01'<effective_to)" -raw).Output.Trim();$june=(DB $fresh "SELECT GROUP_CONCAT(DISTINCT user_id ORDER BY user_id),COUNT(*) FROM approval_role_assignment WHERE enterprise_id='E1' AND organization_id=880001 AND role_code='TEST_APPROVER' AND status='ACTIVE' AND effective_from<='2026-06-01' AND (effective_to IS NULL OR '2026-06-01'<effective_to)" -raw).Output.Trim();Add HISTORICAL_MAY ($may-eq"881001`t2") $may;Add HANDOVER_BOUNDARY ($june-eq"881002`t1") $june
 Reject $fresh overlap_same_source (AssignmentSql 885010 881001 '2026-05-01 00:00:00.000' '' DEC-A 4) 'APPROVAL_ROLE_ASSIGNMENT_OVERLAP'
 Reject $fresh duplicate_assignment $a1
 Reject $fresh revision_update "UPDATE approval_role_revision SET change_reason='x' WHERE id=884001" 'APPROVAL_ROLE_REVISION_APPEND_ONLY';Reject $fresh revision_delete "DELETE FROM approval_role_revision WHERE id=884001" 'APPROVAL_ROLE_REVISION_APPEND_ONLY';Reject $fresh assignment_delete "DELETE FROM approval_role_assignment WHERE id=885001" 'APPROVAL_ROLE_ASSIGNMENT_DELETE_FORBIDDEN';Reject $fresh head_non_cas "UPDATE approval_role_revision_head SET current_revision=3,current_result_hash=REPEAT('c',64),version=1 WHERE id=883001" 'APPROVAL_ROLE_REVISION_HEAD_CAS_ONLY'
 $tx=DB $fresh "START TRANSACTION; INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by,deleted,delete_token,version) VALUES(886001,'E1',880001,'TEST_APPROVER',2,REPEAT('b',64),'BATCH','rollback','2026-07-01','2026-07-01','t',1,REPEAT('a',64),'t','t',0,0,0); INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by,deleted,delete_token,version) VALUES(886002,'E1',880001,'TEST_APPROVER',2,REPEAT('c',64),'BATCH','duplicate','2026-07-01','2026-07-01','t',1,REPEAT('a',64),'t','t',0,0,0); COMMIT";$count=(DB $fresh 'SELECT COUNT(*) FROM approval_role_revision WHERE id IN (886001,886002)' -raw).Output.Trim();Add TRANSACTION_ROLLBACK ($tx.ExitCode-ne0-and$count-eq'0') "$($tx.Output) count=$count"
 $sessionTemplate={param($id,$user,$ref,$sleep) "START TRANSACTION; SELECT current_revision,current_result_hash,version INTO @r,@h,@v FROM approval_role_revision_head WHERE id=883001 FOR UPDATE; $((AssignmentSql $id $user '2026-07-01 00:00:00.000' '' $ref 5)); INSERT INTO approval_role_revision(id,enterprise_id,organization_id,role_code,revision,result_hash,change_type,change_reason,effective_from,published_at,published_by,previous_revision,previous_result_hash,create_by,update_by,deleted,delete_token,version) VALUES($($id+100),'E1',880001,'TEST_APPROVER',@r+1,SHA2(CONCAT('revision',@r+1),256),'ASSIGN','concurrent','2026-07-01','2026-07-01','test',@r,@h,'test','test',0,0,0); UPDATE approval_role_revision_head SET current_revision=@r+1,current_result_hash=SHA2(CONCAT('revision',@r+1),256),version=@v+1,update_by='test' WHERE id=883001 AND version=@v; SELECT SLEEP($sleep); COMMIT;"}
 $c=Concurrent $fresh revision-concurrent (&$sessionTemplate 887001 881001 REV-C1 1) (&$sessionTemplate 887002 881002 REV-C2 0);$head=(DB $fresh 'SELECT current_revision,version FROM approval_role_revision_head WHERE id=883001' -raw).Output.Trim();$facts=(DB $fresh "SELECT COUNT(*) FROM approval_role_assignment WHERE id IN (887001,887002)" -raw).Output.Trim();Add REVISION_CONCURRENCY (!$c.deadlock-and$c.errors-eq0-and$head-eq"3`t2"-and$facts-eq'2') "head=$head facts=$facts $($c.text)"
 $same1=(&$sessionTemplate 888001 881003 SAME-REF 1);$same2=(&$sessionTemplate 888002 881003 SAME-REF 0);$same2=$same2.Replace("SHA2(CONCAT('888002','SAME-REF'),256)","SHA2(CONCAT('888001','SAME-REF'),256)");$d=Concurrent $fresh duplicate-concurrent $same1 $same2;$sameCount=(DB $fresh "SELECT COUNT(*) FROM approval_role_assignment WHERE source_reference='SAME-REF'" -raw).Output.Trim();Add ASSIGNMENT_CONCURRENCY (!$d.deadlock-and$d.errors-eq1-and$sameCount-eq'1') "count=$sameCount $($d.text)"
 $summary=[ordered]@{result=if($failures.Count){'FAIL'}else{'PASS'};outputRoot=$OutputRoot;mysql=(&$mysql --version);flyway=((&$flyway -v 2>&1)-join' ');sha256=(Get-FileHash (Join-Path $migrationRoot 'V2.6.17__create_approval_role_directory.sql') -Algorithm SHA256).Hash.ToLower();flywayChecksum=$checksum;freshFingerprint=$ff;upgradeFingerprint=$uf;checks=$checks;failures=$failures};$summary|ConvertTo-Json -Depth 8|Set-Content (Join-Path $evidence summary.json);$summary|ConvertTo-Json -Depth 8;if($failures.Count){exit 2}
}finally{foreach($s in @($fresh,$upgrade)){if($null-ne$s){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';&$mysqladmin --protocol=TCP --host=127.0.0.1 --port=$s.Port --user=root shutdown 2>$null|Out-Null;$ErrorActionPreference=$old}};foreach($p in $servers){if(!$p.HasExited){Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue}}}
